// Renders the three committed generated modules from the doompiWeb manifest
// scan and keeps them fresh: write-if-changed locally, check-only (throw) in
// CI. Both vite.config.ts and tsdown.config.ts call ensureWebPluginModules at
// config-load time, so `pnpm build` and `pnpm dev` never run against a stale
// registry without saying so.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { scanWebPlugins } from './scan.mjs';

const HEADER = '// Generated by scripts/webPlugins/generate.mjs. Do not edit by hand.';
const packageRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..', '..');

const CLIENT_MODULE = path.join('src', 'web', 'app', 'webPlugins.generated.ts');
const HUB_MODULE = path.join('src', 'adapters', 'webHubPlugins.generated.ts');
const CSS_MODULE = path.join('src', 'web', 'styles', 'webPluginSources.generated.css');

function camel(pluginId) {
  return pluginId.replace(/-([a-z0-9])/g, (_, ch) => ch.toUpperCase());
}

function relativeImport(fromDir, toFile) {
  const spec = path.relative(fromDir, toFile).split(path.sep).join('/');
  return spec.startsWith('.') ? spec : `./${spec}`;
}

function renderClientModule(plugins) {
  const lines = [HEADER, "import type { WebPluginDefinition } from '@agimon-ai/doompi-web-contracts';"];
  const names = [];
  for (const plugin of plugins) {
    const name = `${camel(plugin.pluginId)}Plugin`;
    names.push(name);
    const specifier = plugin.isHost
      ? relativeImport(path.join(packageRoot, 'src', 'web', 'app'), path.join(plugin.packageDir, plugin.client.entry))
      : plugin.client.specifier;
    lines.push(`import { webPlugin as ${name} } from '${specifier}';`);
  }
  lines.push('', `export const webPlugins: readonly WebPluginDefinition[] = [${names.join(', ')}];`, '');
  return lines.join('\n');
}

function renderHubModule(plugins) {
  const lines = [HEADER, "import type { WebHubChannel } from '@agimon-ai/doompi-web-contracts';"];
  const builtinNames = [];
  const externals = [];
  for (const plugin of plugins) {
    if (plugin.hub === undefined) continue;
    if (plugin.isHost) {
      const name = `${camel(plugin.pluginId)}Channels`;
      builtinNames.push(name);
      const specifier = relativeImport(
        path.join(packageRoot, 'src', 'adapters'),
        path.join(plugin.packageDir, plugin.hub.entry),
      );
      lines.push(`import { webHubChannels as ${name} } from '${specifier}';`);
    } else {
      externals.push(plugin);
    }
  }
  lines.push('');
  lines.push(
    builtinNames.length === 0
      ? 'export const BUILTIN_HUB_CHANNELS: readonly WebHubChannel[] = [];'
      : `export const BUILTIN_HUB_CHANNELS: readonly WebHubChannel[] = [${builtinNames.map((name) => `...${name}`).join(', ')}];`,
  );
  lines.push('');
  lines.push('export interface ExternalHubPlugin {');
  lines.push('  pluginId: string;');
  lines.push('  specifier: string;');
  lines.push('  channels: readonly string[];');
  lines.push('}');
  lines.push('');
  if (externals.length === 0) {
    lines.push('export const EXTERNAL_HUB_PLUGINS: readonly ExternalHubPlugin[] = [];');
  } else {
    lines.push('export const EXTERNAL_HUB_PLUGINS: readonly ExternalHubPlugin[] = [');
    for (const plugin of externals) {
      lines.push(
        `  { pluginId: '${plugin.pluginId}', specifier: '${plugin.hub.specifier}', channels: [${plugin.channels.map((channel) => `'${channel}'`).join(', ')}] },`,
      );
    }
    lines.push('];');
  }
  lines.push('');
  return lines.join('\n');
}

function renderCssModule(plugins) {
  const lines = [`/* ${HEADER.slice(3)} */`];
  for (const plugin of plugins) {
    if (plugin.isHost) continue; // The host's own tree is already inside Tailwind's scan root.
    const entryDir = path.dirname(path.join(plugin.packageDir, plugin.client.entry));
    const relative = path
      .relative(path.join(packageRoot, 'src', 'web', 'styles'), entryDir)
      .split(path.sep)
      .join('/');
    lines.push(`@source "${relative}";`);
  }
  lines.push('');
  return lines.join('\n');
}

/** Renders every generated file; exported so the contract test can compare against disk. */
export function renderWebPluginModules() {
  const plugins = scanWebPlugins(packageRoot);
  return new Map([
    [CLIENT_MODULE, renderClientModule(plugins)],
    [HUB_MODULE, renderHubModule(plugins)],
    [CSS_MODULE, renderCssModule(plugins)],
  ]);
}

export function ensureWebPluginModules({ check = false } = {}) {
  const rendered = renderWebPluginModules();
  const stale = [];
  for (const [relativePath, content] of rendered) {
    const filePath = path.join(packageRoot, relativePath);
    const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : undefined;
    if (existing === content) continue;
    if (check) {
      stale.push(relativePath);
      continue;
    }
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content);
  }
  if (stale.length > 0) {
    throw new Error(
      `Stale generated web plugin modules: ${stale.join(', ')}. Run pnpm build in doompi-web and commit them.`,
    );
  }
}
