import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';

import { defineConfig, type UserConfig } from 'tsdown';

export default defineConfig(
  ['session', 'activity'].map((name): UserConfig => {
    const source = `src/extensions/workspaces/sessions/(frontend)/_lib/${name}App`;
    return {
      entry: `${source}.ts`,
      platform: 'browser',
      target: 'es2022',
      tsconfig: 'tsconfig.app.json',
      format: 'iife',
      dts: false,
      sourcemap: false,
      minify: true,
      deps: { alwaysBundle: [/./], onlyBundle: ['@modelcontextprotocol/ext-apps', '@modelcontextprotocol/sdk', 'zod'] },
      write: false,
      clean: false,
      hooks: {
        async 'build:done'({ chunks }) {
          const script = chunks[0];
          if (chunks.length !== 1 || script?.type !== 'chunk' || script.imports.length || script.dynamicImports.length)
            throw new Error(`The ${name} app must be a single self-contained browser script.`);
          const template = await readFile(`${source}.html`, 'utf8');
          if (template.split('<!--APP_SCRIPT-->').length !== 2) throw new Error('Missing unique app script marker.');
          const html = template.replace(
            '<!--APP_SCRIPT-->',
            () => `<script>${script.code.replace(/<\/script/giu, '<\\/script')}</script>`,
          );
          const digest = createHash('sha256').update(html).digest('hex').slice(0, 24);
          const uri = `ui://doompi/${name}/${digest}/index.html`;
          await mkdir('generated/mcp-apps', { recursive: true });
          await writeFile(
            `generated/mcp-apps/${name}.ts`,
            [
              '// Generated by tsdown.app.config.ts. Do not edit by hand.',
              `export const ${name}AppUri = ${JSON.stringify(uri)};`,
              `export const ${name}AppHtml = ${JSON.stringify(html)};`,
              '',
            ].join('\n'),
          );
        },
      },
    };
  }),
);
