import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: {
    leader: 'src/exports/leader.ts',
    extensionName: 'src/exports/extensionName.ts',
    logSinkTelemetry: 'src/exports/logSinkTelemetry.ts',
    toolInventory: 'src/exports/toolInventory.ts',
    footer: 'src/exports/footer.ts',
    toolChrome: 'src/exports/toolChrome.ts',
    uiState: 'src/exports/uiState.ts',
    leaderRegistry: 'src/exports/leaderRegistry.ts',
    harnessMetadata: 'src/exports/harnessMetadata.ts',
    index: 'src/exports/index.ts',
    skills: 'src/exports/skills.ts',
    theme: 'src/exports/theme.ts',
    hashlineRendering: 'src/exports/hashlineRendering.ts',
    rendering: 'src/exports/rendering.ts',
    config: 'src/exports/config.ts',
    'doom-editor': 'src/exports/doomEditor.ts',
    'leader-hints': 'src/exports/leaderHints.ts',
    'matrix-picker': 'src/exports/matrixPicker.ts',
    'doom-footer': 'src/exports/doomFooter.ts',
    'doom-overlay': 'src/exports/doomOverlay.ts',
    'tools-overlay': 'src/exports/toolsOverlay.ts',
    'config-overlay': 'src/exports/configOverlay.ts',
    'doom-header': 'src/exports/doomHeader.ts',
    'extensions/pi': 'src/extensions/pi.ts',
    'extensions/server': 'src/extensions/server.ts',
  },
  clean: true,
  dts: { incremental: true, parallel: false, eager: true },
  exports: false,
  format: ['esm', 'cjs'],
  minify: {
    compress: true,
    mangle: { toplevel: true },
    codegen: { removeWhitespace: true },
  },
  platform: 'node',
  sourcemap: true,
  unbundle: true,
});
