import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

import type { DeclaredWebPlugin } from './webPluginManifest';
import { scanWebPlugins } from './webPluginScan';

const HEADER = '// Generated by doompi web builder. Do not edit by hand.';
export const BUILTIN_CLIENT_MODULE = path.join('src', 'web', 'app', 'webPlugins.generated.ts');
export const BUILTIN_CSS_MODULE = path.join('src', 'web', 'styles', 'webPluginSources.generated.css');

function camel(pluginId: string): string {
  return pluginId.replace(/-([a-z0-9])/g, (_, ch: string) => ch.toUpperCase());
}

function relativeImport(fromDir: string, toFile: string): string {
  const spec = path.relative(fromDir, toFile).split(path.sep).join('/');
  return spec.startsWith('.') ? spec : `./${spec}`;
}

function renderClientModule(
  plugins: readonly DeclaredWebPlugin[],
  style: 'relative' | 'absolute',
  packageRoot: string,
): string {
  const lines = [HEADER, "import type { WebPluginDefinition } from '@agimon-ai/doompi-core/web';"];
  const names: string[] = [];
  const fromDir = path.join(packageRoot, 'src', 'web', 'app');
  for (const plugin of plugins) {
    const name = `${camel(plugin.pluginId)}Plugin`;
    names.push(name);
    const entry = path.join(plugin.packageDir, plugin.client.entry);
    // The committed builtin module keeps machine-neutral relative imports; the
    // sync-generated module lives outside src, is aliased over the committed
    // path, and resolves imports against its real location, so every entry
    // becomes an absolute file URL into the installed packages.
    const specifier = style === 'relative' ? relativeImport(fromDir, entry) : pathToFileURL(entry).href;
    lines.push(`import { webPlugin as ${name} } from '${specifier}';`);
  }
  lines.push('', `export const webPlugins: readonly WebPluginDefinition[] = [${names.join(', ')}];`, '');
  return lines.join('\n');
}

/**
 * The directory Tailwind scans for a plugin's class names.
 *
 * A plugin's components live in its `src/web` root. The client entry is not a
 * reliable stand-in: it is published through `src/exports/webClient.ts`, a
 * one-line re-export, and pointing Tailwind at that directory silently drops
 * every class the panels use. The entry's own directory is the fallback for a
 * plugin that keeps no src/web root at all.
 */
function pluginSourceRoot(plugin: DeclaredWebPlugin): string {
  const webRoot = path.join(plugin.packageDir, 'src', 'web');
  if (fs.existsSync(webRoot)) return webRoot;
  return path.dirname(path.join(plugin.packageDir, plugin.client.entry));
}

function renderCssModule(plugins: readonly DeclaredWebPlugin[], leadingSourceRoots: readonly string[]): string {
  // Sync CSS is compiled from a generated directory, so Tailwind cannot infer
  // the stable shell tree from app.css. Its caller names that tree explicitly
  // so later plugin utilities do not override missing responsive shell utilities.
  const lines = [`/* ${HEADER.slice(3)} */`, ...leadingSourceRoots.map((root) => `@source "${root}";`)];
  for (const plugin of plugins) {
    if (plugin.isHost) continue;
    lines.push(`@source "${pluginSourceRoot(plugin)}";`);
  }
  lines.push('');
  return lines.join('\n');
}

/** The committed client registry, rendered from the host package alone. */
export function renderBuiltinWebPluginModules(packageRoot: string): Map<string, string> {
  const plugins = scanWebPlugins(packageRoot);
  return new Map([
    [BUILTIN_CLIENT_MODULE, renderClientModule(plugins, 'relative', packageRoot)],
    [BUILTIN_CSS_MODULE, renderCssModule(plugins, [])],
  ]);
}

/**
 * Keeps the committed client registry fresh: write-if-changed locally,
 * check-only (throw) in CI. Both vite.config.ts and tsdown.config.ts call
 * this at config-load time.
 */
export function ensureBuiltinWebPluginModules({
  packageRoot,
  check = false,
}: {
  packageRoot: string;
  check?: boolean;
}): void {
  const stale: string[] = [];
  for (const [relativePath, content] of renderBuiltinWebPluginModules(packageRoot)) {
    const filePath = path.join(packageRoot, relativePath);
    const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : undefined;
    if (existing === content) continue;
    if (check) {
      stale.push(relativePath);
      continue;
    }
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content);
  }
  if (stale.length > 0) {
    throw new Error(
      `Stale generated web plugin modules: ${stale.join(', ')}. Run pnpm build in doompi-web and commit them.`,
    );
  }
}

export interface SyncGeneratedModules {
  clientModulePath: string;
  compositionModulePath: string;
  cssModulePath: string;
}

/**
 * The sync-time variant: renders the full client plugin set (host built-ins plus
 * the installed composition's packages) into a generation directory the bundler
 * aliases over the committed builtin modules.
 */
export function writeSyncWebPluginModules(
  plugins: readonly DeclaredWebPlugin[],
  generatedDir: string,
  packageRoot: string,
): SyncGeneratedModules {
  fs.mkdirSync(generatedDir, { recursive: true });
  const clientModulePath = path.join(generatedDir, 'webPlugins.generated.ts');
  const compositionModulePath = path.join(generatedDir, 'webPluginComposition.generated.ts');
  const cssModulePath = path.join(generatedDir, 'webPluginSources.generated.css');
  fs.writeFileSync(clientModulePath, renderClientModule(plugins, 'absolute', packageRoot));
  fs.writeFileSync(
    compositionModulePath,
    `${HEADER}\nimport '${pathToFileURL(path.join(packageRoot, 'src', 'web', 'styles', 'app.css')).href}';\nimport { webPlugins } from './webPlugins.generated.ts';\n\nglobalThis.DoomPiWebPluginComposition = webPlugins;\n`,
  );
  fs.writeFileSync(cssModulePath, renderCssModule(plugins, [path.join(packageRoot, 'src', 'web')]));
  return {
    clientModulePath,
    compositionModulePath,
    cssModulePath,
  };
}
