export {
  composeRootHooks,
  defineActivity,
  defineChannel,
  defineCliTool,
  defineCommand,
  defineHook,
  defineMethod,
  defineMode,
  defineProvider,
  defineResource,
  defineRoot,
  defineRoutedContribution,
  defineRoute,
  defineServerTool,
  defineShortcut,
  defineService,
  defineTool,
  defineToolRestriction,
} from '../extensions/extensionFile';
export type {
  ActivityFile,
  ChannelFile,
  CliToolFile,
  CommandContribution,
  CommandFile,
  HookFile,
  MethodFile,
  OrFactory,
  PathSupplied,
  RootDeclaration,
  RootFile,
  RoutedCardinality,
  RoutedFileOptions,
  RouteFile,
  ServerToolFile,
  ServiceFile,
  ToolContribution,
  ToolFile,
  WithRoot,
} from '../schemas/extensionFile';
