export {
  composeRootHooks,
  defineActivity,
  defineChannel,
  defineCliTool,
  defineCommand,
  defineHook,
  defineMethod,
  defineRoot,
  defineRoute,
  defineServerTool,
  defineService,
  defineTool,
} from '../extensions/extensionFile';
export type {
  ActivityFile,
  ChannelFile,
  CliToolFile,
  CommandContribution,
  CommandFile,
  HookFile,
  MethodFile,
  OrFactory,
  PathSupplied,
  RootDeclaration,
  RootFile,
  RouteFile,
  ServerToolFile,
  ServiceFile,
  ToolContribution,
  ToolFile,
  WithRoot,
} from '../schemas/extensionFile';
