export {
  bindSessionApiWorkspace,
  globalApiPath,
  sessionApiAddress,
  sessionApiPath,
  workspaceApiPath,
} from '../web/services/apiRoutes';
export {
  apiQueryString,
  pluginApiBase,
  pluginApiUrl,
  applyPathParams,
  scopeApiRoot,
  SETTINGS_BASE_PATH,
  type ApiParams,
  type ApiQuery,
  type ApiScopeAddress,
} from '../web/services/apiPaths';
export {
  apiResponse,
  createApiClient,
  defineApiRoutes,
  type ApiCallInit,
  type ApiClient,
  type ApiClientOptions,
  type ApiMethod,
  type ApiResponseOf,
  type ApiResult,
  type ApiRouteMethod,
  type ApiRoutes,
  type ApiRouteSpec,
  type ApiScopeClient,
  type ApiScopeName,
  type ApiStreamMethod,
  type ApiTransport,
} from '../web/services/apiClient';
export {
  defineActivityGroup,
  defineChannelFile,
  defineContextAction,
  defineDockFace,
  defineFileLinks,
  defineFill,
  defineLeaderBinding,
  defineMinorModeFile,
  definePaletteCommand,
  defineRepositorySettingsPanel,
  defineSelectionAxis,
  defineSessionChannel,
  defineSettingsPanel,
  defineSettingsSection,
  defineSlot,
  defineSlotFile,
  defineTab,
  defineToolRenderer,
  defineUserMessageAction,
  defineWebLifecycle,
  defineWebPlugin,
} from '../extensions/webPlugin';
export type {
  ActivityGroupFile,
  ChannelFile,
  ContextActionFile,
  DockFaceFile,
  FillFile,
  LeaderBindingFile,
  MinorModeFile,
  PaletteCommandFile,
  SelectionAxisFile,
  SettingsPanelFile,
  SettingsSectionFile,
  SlotFile,
  TabFile,
  ToolRendererFile,
  UserMessageActionFile,
} from '../web/types/extensionFile';
export { defineGlobalStore } from '../web/models/globalStore';
export { defineSessionStore } from '../web/models/sessionStore';
export { defineWorkspaceStore } from '../web/models/workspaceStore';
export {
  HUB_ADVERTISEMENT_VERSION,
  hubAdvertisementPath,
  parseHubAdvertisement,
  parseSessionLineage,
  REGISTRY_DIR_ENV,
  resolveRegistryDir,
  SESSION_LINEAGE_RECORD_VERSION,
  sessionLineagePath,
} from '../web/services/sessionRegistry';
export { toolResultText, toolResultTextLines } from '../web/services/toolResult';
export type { HubAdvertisement, RegistryDirInput, SessionLineageRecord } from '../web/types/sessionRegistry';
export type {
  ModelContext,
  ModelContextAbortSignal,
  ModelContextBinding,
  ModelContextExecutionOptions,
  ModelContextRegistrationOptions,
  ModelContextTool,
  ModelContextToolChangeEvent,
  ModelContextToolChangeListener,
  ModelContextToolDescriptor,
} from '../web/types/modelContext';
export type {
  WebPluginScope,
  WebPluginContributions,
  WebPluginMount,
  ActivityGroupContribution,
  ComposerCapture,
  ComposerSubmission,
  CaptureStatusEvent,
  ContextAction,
  ContextActionContribution,
  ContextActionRunContext,
  DockFaceContribution,
  FileLinkSource,
  GlobalStore,
  LeaderBindingContribution,
  LeaderKeyContribution,
  MinorModeContribution,
  PaletteCommandContext,
  PaletteCommandContribution,
  RepositorySettingsPanelContribution,
  RepositorySettingsPanelProps,
  RepositorySettingsRepository,
  SelectionAxisContribution,
  SessionChannelContribution,
  SessionFrameSender,
  SessionRecords,
  SessionStore,
  SessionStoreChannel,
  SettingsFieldContribution,
  SettingsFieldOption,
  SettingsPanelContribution,
  SettingsPanelProps,
  SettingsSectionContribution,
  SlotDataFill,
  SlotDeclaration,
  SlotFillContribution,
  SurfaceContribution,
  TabContribution,
  ThreadViewOptions,
  ToolMessageRenderProps,
  ToolPromptContribution,
  ToolPromptDialog,
  ToolPromptRenderProps,
  ToolRendererContribution,
  ToolResultView,
  TransientTab,
  UserMessageActionContribution,
  UserMessageActionRunContext,
  WebPluginContextInventoryItem,
  WebPluginContextItem,
  WebPluginDefinition,
  WebPluginRuntime,
  WebPluginSlotProps,
  WorkspaceRecords,
  WorkspaceStore,
} from '../web/types/webPlugin';

export {
  BUNDLE_ASSET_POLICY_PATH,
  BUNDLE_ASSET_POLICY_VERSION,
  parseBundleAssetPolicy,
  type BundleAssetPolicy,
} from '../web/schemas/bundleAssetPolicy';
