import { posix } from 'node:path';

import type { ExtensionGraph } from '../../types/extensionGraph';
import { toSnake } from '../identity';

/** Browser entries are paired by their routed identity, never imported into the Node MCP facet. */
export function renderMcpWidgets(graph: ExtensionGraph, packageName: string, entryDir: string) {
  const declarations: Record<string, string> = {};
  const imports: string[] = [];
  const members: string[] = [];
  const names = new Set<string>();
  const widgets = graph.entries
    .filter((entry) => entry.side === 'frontend' && entry.platform === 'mcp' && entry.surface === 'tool')
    .sort((left, right) => left.file.localeCompare(right.file));
  for (const [index, entry] of widgets.entries()) {
    const name = toSnake(entry.name);
    const key = `${packageName}/${name}`;
    if (names.has(key)) throw new Error(`Duplicate MCP widget '${key}'`);
    const tools = graph.entries.filter(
      (candidate) =>
        candidate.side === 'backend' &&
        candidate.platform === 'mcp' &&
        candidate.surface === 'tool' &&
        toSnake(candidate.name) === name &&
        JSON.stringify(candidate.gates) === JSON.stringify(entry.gates),
    );
    if (tools.length !== 1)
      throw new Error(`MCP widget '${entry.file}' must match exactly one backend tool declaration`);
    names.add(key);
    declarations[tools[0]!.file] = key;
    const relative = posix.relative(entryDir, entry.file.replace(/\.[^.]+$/u, ''));
    imports.push(
      `import Widget${index} from ${JSON.stringify(relative.startsWith('.') ? relative : `./${relative}`)};`,
    );
    members.push(`  ${JSON.stringify(key)}: Widget${index},`);
  }
  return {
    declarations,
    names: [...names],
    source:
      widgets.length === 0
        ? undefined
        : [
            '// Generated by @agimon-ai/doompi-build. Do not edit by hand.',
            "import type { ComponentType } from 'react';",
            "import type { DoomMcpWidgetProps } from '@agimon-ai/doompi-core/mcpWidget';",
            ...imports,
            '',
            'export const widgets: Readonly<Record<string, ComponentType<DoomMcpWidgetProps>>> = {',
            ...members,
            '};',
            '',
          ].join('\n'),
  };
}
