export { writePrivateAtomicJson } from '../services/atomicJson';
export {
  globalDoomConfigDirectory,
  globalDoomConfigPath,
  loadDoomConfig,
  loadDoomConfigAsync,
  loadDoomConfigLayers,
  loadDoomConfigLenient,
  repositoryDoomConfigPath,
  resolvePlanningPlansDirectory,
} from '../services/config';
export {
  DOOM_PLANNING_THINKING_LEVELS,
  DOOM_VOICE_ENGINES,
  DOOM_VOICE_MODES,
  DOOM_VOICE_TTS_ENGINES,
  configLeafKeys,
  configRootKeys,
  configScopeOf,
  mergeDoomConfigs,
  parseAutocompactModeConfig,
  parseDoomConfig,
  parsePlanningModeConfig,
  resolveVoiceConfig,
  valueAtKeyPath,
  type ConfigKeyScope,
} from '../services/configPolicy';
export {
  setDoomConfigValue,
  unsetDoomConfigValue,
  writeDoomConfigValues,
  type DoomConfigEdit,
  type DoomConfigScope,
  type WriteDoomConfigOptions,
} from '../services/configWriter';
export {
  DOOM_DIR,
  listDomainNames,
  loadDomains,
  resolvePluginDirectories,
  resolvePluginEntries,
  resolveSharedSkills,
} from '../services/domains';
export { domainCompletionItems, domainCompletionPrefix, expandDomainNames } from '../services/domains/completion';
export {
  FILE_ONLY_STATE_FIELDS,
  HARNESS_STATE_KEYS,
  projectHarnessEnvironment,
  readHarnessState,
  type HarnessStateParseReporter,
} from '../services/harnessState';
export {
  HARNESS_STATE_POINTER,
  createHarnessSession,
  disposeHarnessState,
  getHarnessState,
  harnessRoot,
  loadHarnessState,
  requireHarnessPaths,
  requireHarnessRoot,
  resetHarnessStore,
  restoreHarnessStateSnapshot,
  snapshotHarnessState,
  updateHarnessState,
  type HarnessStateFile,
  type HarnessStateTransactionSnapshot,
} from '../services/harnessStore';
export {
  DEFAULT_IMAGE_MAX_DIMENSION,
  MIN_IMAGE_MAX_DIMENSION,
  clampImageMaxDimension,
  parsePiImageSettings,
  type PiImageSettings,
  type PiImageSettingsUpdate,
} from '../services/imageSettings';
export {
  DOOM_CONFIG_TEMPLATES,
  GLOBAL_DOOM_SEED_FILES,
  REPOSITORY_DOOM_CONFIG_TEMPLATES,
  initializeGlobalDoomConfig,
  initializeRepositoryDoomConfig,
  type GlobalDoomInitResult,
  type RepositoryDoomInitOptions,
  type RepositoryDoomInitResult,
} from '../services/init';
export {
  isLocalPackageSpecifier,
  layerEntries,
  layerHookGroups,
  loadMajorModesConfig,
  loadMajorModesConfigLenient,
  resolveLayers,
  resolvePackageConfigurations,
} from '../services/majorModes';
export type {
  LayerDefinition,
  LayerPackage,
  LayerPackageConfig,
  LayerResolvers,
  MajorModeDefinition,
  MajorModesConfig,
  ResolvedLayerDefinition,
  ResolvedPackageConfiguration,
} from '../services/majorModes';
export {
  loadPiConfig,
  loadPiConfigAsync,
  loadPiImageSettings,
  piConfigPaths,
  piImageSettingsPath,
  savePiImageSettings,
} from '../services/piConfig';
export {
  MARKETPLACE_MANIFEST_RELATIVE_PATHS,
  findPluginManifestPath,
  isRemotePluginSource,
  pluginDirectoryForSource,
} from '../services/pluginCatalog';
export {
  PERSONA_FILES,
  applyProfileEnvironment,
  buildPersonaPrompt,
  listProfileNames,
  loadProfiles,
  replaceProfileEnvironment,
  resolveProfile,
} from '../services/profiles';
export type { AgentProfile } from '../services/profiles';
export {
  DOOM_CONFIG_ENTRY_TYPE,
  DOOM_CONFIG_TRANSITION_ENTRY_TYPE,
  acknowledgeDoomConfigTransition,
  appendDoomConfigSelection,
  appendDoomConfigTransition,
  createDoomConfigContext,
  createDoomConfigContextAsync,
  freezeDoomConfigContext,
  provideDoomConfigContext,
  readDoomConfigContextGeneration,
  readDoomConfigPendingSelection,
  readDoomConfigSelection,
  replaceDoomConfigContext,
  requireDoomConfigContext,
  supersedeDoomConfigTransition,
  type DoomConfigSelection,
} from '../services/sessionConfig';
export {
  DOOM_CONFIG_SERVICE,
  type AutocompactModeConfig,
  type AutocompactOverrideConfig,
  type AutocompactThresholdConfig,
  type AutocompactTokenConfig,
  type DeepReadonly,
  type DoomConfig,
  type DoomConfigContext,
  type DoomHarnessContext,
  type DoomSelectionConfig,
  type EditorConfig,
  type HarnessState,
  type IDoomConfigLoader,
  type IDoomConfigService,
  type PackageAttribution,
  type PlanningAgentConfig,
  type PlanningModeConfig,
  type PlanningThinkingLevel,
  type PluginHookSource,
  type ProjectTrust,
  type ResolvedVoiceAutoCaptureConfig,
  type ResolvedVoiceConfig,
  type VoiceAdapterConfig,
  type VoiceAutoCaptureConfig,
  type VoiceConfig,
  type VoiceEngine,
  type VoiceMode,
  type VoiceModelConfig,
  type VoiceTtsConfig,
  type VoiceTtsEngine,
} from '../types/config';
export type {
  ConfigValueOrigin,
  DoomConfigLayer,
  DoomConfigLayers,
  DoomConfigPendingSelection,
  DoomConfigTransitionPhase,
  DoomConfigTransitionRecord,
  DoomConfigTransitionStrategy,
} from '../types/config';
export type {
  DomainDefinition,
  DomainManifest,
  DomainMcpAllowlist,
  DomainPlugin,
  GitPluginSource,
  LocalPluginSource,
  NpmPluginSource,
  PluginCatalog,
  PluginCatalogEntry,
  PluginEntry,
  PluginManifestMetadata,
  PluginSkillDiscovery,
  PluginSource,
  ResolvedDomain,
} from '../types/domains';
export type { ConfigAdapterRegistrationOptions, PiConfig, PiConfigLoadOptions, PiConfigPaths } from '../types/piConfig';

export type { LoadedHarnessState } from '../models/harnessCache';
