// Generated by src/adapters/webPluginGenerate.ts. Do not edit by hand.
import type { WebHubChannel } from '@agimon-ai/doompi-web-contracts';

export const BUILTIN_HUB_CHANNELS: readonly WebHubChannel[] = [];
