import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: {
    'api-contracts': 'src/exports/apiContracts.ts',
    'store-process-liveness': 'src/exports/storeProcessLiveness.ts',
    'delegation-manager': 'src/exports/delegationManager.ts',
    logSinkTelemetry: 'src/exports/logSinkTelemetry.ts',
    commands: 'src/exports/commands.ts',
    'store-invariants': 'src/exports/storeInvariants.ts',
    'store-task-graph': 'src/exports/storeTaskGraph.ts',
    'tool-response-envelope': 'src/exports/toolResponseEnvelope.ts',
    'tui-task-overlay': 'src/exports/tuiTaskOverlay.ts',
    'store-reconcile': 'src/exports/storeReconcile.ts',
    'tui-selectors': 'src/exports/tuiSelectors.ts',
    'tool-prompt-guidelines': 'src/exports/toolPromptGuidelines.ts',
    'store-task-store': 'src/exports/storeTaskStore.ts',
    'tui-format': 'src/exports/tuiFormat.ts',
    'tui-task-space': 'src/exports/tuiTaskSpace.ts',
    'store-reducer': 'src/exports/storeReducer.ts',
    'store-paths': 'src/exports/storePaths.ts',
    'tool-schema': 'src/exports/toolSchema.ts',
    index: 'src/exports/index.ts',
    'store-types': 'src/exports/storeTypes.ts',
    config: 'src/exports/config.ts',
    'tool-task-tool': 'src/exports/toolTaskTool.ts',
    'extensions/pi': 'src/extensions/pi.ts',
    'extensions/server': 'src/extensions/server.ts',
  },
  clean: true,
  dts: { incremental: true, parallel: false, eager: true },
  exports: false,
  format: ['esm', 'cjs'],
  minify: {
    compress: true,
    mangle: { toplevel: true },
    codegen: { removeWhitespace: true },
  },
  platform: 'node',
  sourcemap: true,
  unbundle: true,
});
