import fs from 'node:fs';
import path from 'node:path';
import { type DomainMcpAllowlist, expandDomainNames, loadDomains } from '@agimon-ai/doompi-config/domains';
import { parse as parseYaml, stringify as stringifyYaml } from 'yaml';
import type { JsonObject } from '../types/resources.ts';

/** Server name in .mcp.json whose upstreams are declared in mcp-config.yaml. */
export const PROXY_SERVER_NAME = 'agiflow-proxy';
const PROXY_CONFIG_FILE = 'mcp-config.yaml';
const CONFIG_ARGUMENT = '--config';

/**
 * Unions the mcp allowlists of the selected domains.
 *
 * Returns undefined when any selected domain omits `mcp`, which means "give me
 * everything". Filtering only kicks in once every selected domain has opted in,
 * so a domain that has not been migrated yet cannot silently lose its tools.
 */
export function resolveMcpAllowlist(repoRoot: string, domainNames: string[]): DomainMcpAllowlist | undefined {
  const manifest = loadDomains(repoRoot);
  const expanded = expandDomainNames(manifest, domainNames);
  if (expanded.length === 0) return undefined;

  const servers = new Set<string>();
  const proxy = new Set<string>();
  for (const name of expanded) {
    const allowlist = manifest.domains[name]?.mcp;
    if (!allowlist) return undefined;
    for (const server of allowlist.servers ?? []) servers.add(server);
    for (const upstream of allowlist.proxy ?? []) proxy.add(upstream);
  }
  return { servers: [...servers], proxy: [...proxy] };
}

/** Drops servers that are not on the allowlist. An empty list means keep all. */
export function filterMcpServers(config: JsonObject, allowed?: string[]): JsonObject {
  if (!allowed || allowed.length === 0) return config;
  const servers = (config.mcpServers ?? {}) as Record<string, unknown>;
  const kept: Record<string, unknown> = {};
  for (const [name, definition] of Object.entries(servers)) {
    if (allowed.includes(name)) kept[name] = definition;
  }
  return { ...config, mcpServers: kept };
}

/**
 * Rewrites the proxy's upstream list, keeping only allowed servers.
 *
 * Entries are removed rather than marked disabled so a filtered upstream cannot
 * be reached even if the proxy ignores the disabled flag. Comments in the
 * source file are not preserved; the result is a per-run temporary file.
 */
export function filterProxyConfig(yamlText: string, allowed?: string[]): string {
  if (!allowed || allowed.length === 0) return yamlText;
  const config = (parseYaml(yamlText) ?? {}) as JsonObject;
  const servers = (config.mcpServers ?? {}) as Record<string, unknown>;
  const kept: Record<string, unknown> = {};
  const dropped: string[] = [];
  for (const [name, definition] of Object.entries(servers)) {
    if (allowed.includes(name)) kept[name] = definition;
    else dropped.push(name);
  }
  const header = [
    '# Generated by doompi for this run. Do not edit.',
    `# Upstreams kept: ${Object.keys(kept).join(', ') || '(none)'}`,
    `# Upstreams removed by the domain allowlist: ${dropped.join(', ') || '(none)'}`,
    '',
  ].join('\n');
  return `${header}${stringifyYaml({ ...config, mcpServers: kept })}`;
}

async function copyFileIfPresent(source: string, target: string): Promise<boolean> {
  try {
    await fs.promises.copyFile(source, target);
    return true;
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return false;
    throw error;
  }
}

/**
 * Copies a generated MCP config out of the run directory so another frontend
 * can use it, keeping the proxy's --config pointing at the copy.
 *
 * The run directory is deleted when the harness exits, so emitting for
 * claude.sh or codex.sh has to relocate both files together.
 */
export async function persistMcpConfig(
  sourceConfigPath: string,
  temporaryDirectory: string,
  targetDirectory: string,
): Promise<string> {
  await fs.promises.mkdir(targetDirectory, { recursive: true });
  const config = JSON.parse(await fs.promises.readFile(sourceConfigPath, 'utf8')) as JsonObject;
  const servers = (config.mcpServers ?? {}) as Record<string, JsonObject>;
  const proxy = servers[PROXY_SERVER_NAME];
  const generatedProxyConfig = path.join(temporaryDirectory, PROXY_CONFIG_FILE);

  if (proxy) {
    const args = [...((proxy.args ?? []) as string[])];
    const configIndex = args.indexOf(CONFIG_ARGUMENT);
    if (configIndex !== -1) {
      const targetProxyConfig = path.join(targetDirectory, PROXY_CONFIG_FILE);
      if (await copyFileIfPresent(generatedProxyConfig, targetProxyConfig)) {
        args[configIndex + 1] = targetProxyConfig;
        servers[PROXY_SERVER_NAME] = { ...proxy, args };
      }
    }
  }

  const targetPath = path.join(targetDirectory, 'mcp.json');
  await fs.promises.writeFile(targetPath, `${JSON.stringify({ ...config, mcpServers: servers }, null, 2)}\n`, {
    mode: 0o600,
  });
  return targetPath;
}

/**
 * Applies the allowlist to a merged MCP config, writing a filtered proxy config
 * into the run directory and repointing the proxy at it when needed.
 */
export async function applyMcpAllowlist(
  config: JsonObject,
  allowlist: DomainMcpAllowlist | undefined,
  repoRoot: string,
  temporaryDirectory: string,
): Promise<JsonObject> {
  if (!allowlist) return config;
  const filtered = filterMcpServers(config, allowlist.servers);
  const servers = (filtered.mcpServers ?? {}) as Record<string, JsonObject>;
  const proxy = servers[PROXY_SERVER_NAME];
  if (!proxy || !allowlist.proxy || allowlist.proxy.length === 0) return filtered;

  const args = [...((proxy.args ?? []) as string[])];
  const configIndex = args.indexOf(CONFIG_ARGUMENT);
  if (configIndex === -1 || !args[configIndex + 1]) return filtered;

  const sourcePath = path.resolve(repoRoot, args[configIndex + 1]);
  let sourceConfig: string;
  try {
    sourceConfig = await fs.promises.readFile(sourcePath, 'utf8');
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return filtered;
    throw error;
  }
  const targetPath = path.join(temporaryDirectory, PROXY_CONFIG_FILE);
  await fs.promises.writeFile(targetPath, filterProxyConfig(sourceConfig, allowlist.proxy), { mode: 0o600 });
  args[configIndex + 1] = targetPath;
  return { ...filtered, mcpServers: { ...servers, [PROXY_SERVER_NAME]: { ...proxy, args } } };
}
