// Generated by scripts/webPlugins/generate.mjs. Do not edit by hand.
import type { WebPluginDefinition } from '@agimon-ai/doompi-web-contracts';
import { webPlugin as subagentsPlugin } from '../features/subagents/index.ts';
import { webPlugin as workflowsPlugin } from '@agimon-ai/doompi-workflow/web';

export const webPlugins: readonly WebPluginDefinition[] = [subagentsPlugin, workflowsPlugin];
