import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: {
    '*': 'src/exports/**/*.ts',
    'extensions/contextCatalog': 'src/extensions/contextCatalog.ts',
    'bin/cli': 'src/bin/cli.ts',
    'bin/doomRunner': 'src/bin/doomRunner.ts',
    'bin/dpi': 'src/bin/dpi.ts',
    'extensions/pi': 'src/extensions/pi.ts',
    'extensions/server': 'src/extensions/server.ts',
    'extensions/agentModel': 'src/extensions/agentModel.ts',
    'extensions/cordisFinalizer': 'src/extensions/cordisFinalizer.ts',
    'extensions/cordisHost': 'src/extensions/cordisHost.ts',
    'extensions/composedPi': 'src/extensions/composedPi.ts',
    'extensions/effort': 'src/extensions/effort.ts',
    'extensions/terminalChildSession': 'src/extensions/terminalChildSession.ts',
    'extensions/ollamaProvider': 'src/extensions/ollamaProvider.ts',
    'extensions/styleSystem': 'src/extensions/styleSystem.ts',
    'extensions/launcherBootstrap': 'src/extensions/launcherBootstrap.ts',
    'extensions/transitionCoordinator': 'src/extensions/transitionCoordinator.ts',
    'bin/serve': 'src/bin/serve.ts',
    'builders/cli/index': 'src/builders/cli/index.ts',
    'builders/cli/extensionAssembler/index': 'src/builders/cli/extensionAssembler/index.ts',
  },
  clean: true,
  dts: { incremental: true, parallel: false, eager: true },
  exports: false,
  format: { esm: {}, cjs: { dts: false } },
  platform: 'node',
  sourcemap: true,
  unbundle: true,
});
