// Generated by scripts/webPlugins/generate.mjs. Do not edit by hand.
import type { WebHubChannel } from '@agimon-ai/doompi-web-contracts';
import { webHubChannels as subagentsChannels } from './subagentsChannel.ts';

export const BUILTIN_HUB_CHANNELS: readonly WebHubChannel[] = [...subagentsChannels];

export interface ExternalHubPlugin {
  pluginId: string;
  specifier: string;
  channels: readonly string[];
}

export const EXTERNAL_HUB_PLUGINS: readonly ExternalHubPlugin[] = [
  { pluginId: 'workflows', specifier: '@agimon-ai/doompi-workflow/web-hub', channels: ['workflow_runs'] },
];
