// Generated by src/adapters/webPluginGenerate.ts. Do not edit by hand.
import type { WebHubChannel } from '@agimon-ai/doompi-web-contracts';
import { webHubChannels as subagentsChannels } from './subagentsChannel.ts';

export const BUILTIN_HUB_CHANNELS: readonly WebHubChannel[] = [...subagentsChannels];
