import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import type { DeclaredWebPlugin } from '../services/webPluginManifest.ts';
import { scanWebPlugins } from './webPluginScan.ts';

const HEADER = '// Generated by src/adapters/webPluginGenerate.ts. Do not edit by hand.';

/** Walks up to the owning package.json: correct from src and from the unbundled dist tree alike. */
function ownPackageRoot(): string {
  let dir = path.dirname(fileURLToPath(import.meta.url));
  for (;;) {
    if (fs.existsSync(path.join(dir, 'package.json'))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) throw new Error('doompi-web could not locate its own package root.');
    dir = parent;
  }
}

const packageRoot = ownPackageRoot();

export const BUILTIN_CLIENT_MODULE = path.join('src', 'web', 'app', 'webPlugins.generated.ts');
export const BUILTIN_HUB_MODULE = path.join('src', 'adapters', 'webHubPlugins.generated.ts');
export const BUILTIN_CSS_MODULE = path.join('src', 'web', 'styles', 'webPluginSources.generated.css');
/** The server-side registry a synced bundle carries next to its assets. */
export const SERVER_REGISTRY_FILE = 'webPlugins.server.json';

export function webHostPackageRoot(): string {
  return packageRoot;
}

function camel(pluginId: string): string {
  return pluginId.replace(/-([a-z0-9])/g, (_, ch: string) => ch.toUpperCase());
}

function relativeImport(fromDir: string, toFile: string): string {
  const spec = path.relative(fromDir, toFile).split(path.sep).join('/');
  return spec.startsWith('.') ? spec : `./${spec}`;
}

function renderClientModule(plugins: readonly DeclaredWebPlugin[], style: 'relative' | 'absolute'): string {
  const lines = [HEADER, "import type { WebPluginDefinition } from '@agimon-ai/doompi-web-contracts';"];
  const names: string[] = [];
  const fromDir = path.join(packageRoot, 'src', 'web', 'app');
  for (const plugin of plugins) {
    const name = `${camel(plugin.pluginId)}Plugin`;
    names.push(name);
    const entry = path.join(plugin.packageDir, plugin.client.entry);
    // The committed builtin module keeps machine-neutral relative imports; the
    // sync-generated module lives outside src, is aliased over the committed
    // path, and resolves imports against its real location, so every entry
    // becomes an absolute file URL into the installed packages.
    const specifier = style === 'relative' ? relativeImport(fromDir, entry) : pathToFileURL(entry).href;
    lines.push(`import { webPlugin as ${name} } from '${specifier}';`);
  }
  lines.push('', `export const webPlugins: readonly WebPluginDefinition[] = [${names.join(', ')}];`, '');
  return lines.join('\n');
}

function renderBuiltinHubModule(plugins: readonly DeclaredWebPlugin[]): string {
  const lines = [HEADER, "import type { WebHubChannel } from '@agimon-ai/doompi-web-contracts';"];
  const names: string[] = [];
  for (const plugin of plugins) {
    if (plugin.hub === undefined || !plugin.isHost) continue;
    const name = `${camel(plugin.pluginId)}Channels`;
    names.push(name);
    const specifier = relativeImport(
      path.join(packageRoot, 'src', 'adapters'),
      path.join(plugin.packageDir, plugin.hub.entry),
    );
    lines.push(`import { webHubChannels as ${name} } from '${specifier}';`);
  }
  lines.push('');
  lines.push(
    names.length === 0
      ? 'export const BUILTIN_HUB_CHANNELS: readonly WebHubChannel[] = [];'
      : `export const BUILTIN_HUB_CHANNELS: readonly WebHubChannel[] = [${names.map((name) => `...${name}`).join(', ')}];`,
  );
  lines.push('');
  return lines.join('\n');
}

function renderCssModule(plugins: readonly DeclaredWebPlugin[]): string {
  const lines = [`/* ${HEADER.slice(3)} */`];
  for (const plugin of plugins) {
    if (plugin.isHost) continue; // The host tree is already inside Tailwind's scan root.
    lines.push(`@source "${path.dirname(path.join(plugin.packageDir, plugin.client.entry))}";`);
  }
  lines.push('');
  return lines.join('\n');
}

export interface ServerRegistryEntry {
  pluginId: string;
  channels: string[];
  /** Absolute path to the built hub entry exporting webHubChannels. */
  hubEntry: string;
}

function renderServerRegistry(plugins: readonly DeclaredWebPlugin[]): string {
  const entries: ServerRegistryEntry[] = [];
  for (const plugin of plugins) {
    if (plugin.hub === undefined) continue;
    // Host channels are compiled into the server; only externals need loading.
    if (plugin.isHost) continue;
    entries.push({
      pluginId: plugin.pluginId,
      channels: plugin.channels,
      hubEntry: path.join(plugin.packageDir, plugin.hub.dist ?? plugin.hub.entry),
    });
  }
  return `${JSON.stringify(entries, null, 2)}\n`;
}

/** The committed builtin registry, rendered from the host package alone. */
export function renderBuiltinWebPluginModules(): Map<string, string> {
  const plugins = scanWebPlugins(packageRoot);
  return new Map([
    [BUILTIN_CLIENT_MODULE, renderClientModule(plugins, 'relative')],
    [BUILTIN_HUB_MODULE, renderBuiltinHubModule(plugins)],
    [BUILTIN_CSS_MODULE, renderCssModule(plugins)],
  ]);
}

/**
 * Keeps the committed builtin registry fresh: write-if-changed locally,
 * check-only (throw) in CI. Both vite.config.ts and tsdown.config.ts call
 * this at config-load time.
 */
export function ensureBuiltinWebPluginModules({ check = false }: { check?: boolean } = {}): void {
  const stale: string[] = [];
  for (const [relativePath, content] of renderBuiltinWebPluginModules()) {
    const filePath = path.join(packageRoot, relativePath);
    const existing = fs.existsSync(filePath) ? fs.readFileSync(filePath, 'utf8') : undefined;
    if (existing === content) continue;
    if (check) {
      stale.push(relativePath);
      continue;
    }
    fs.mkdirSync(path.dirname(filePath), { recursive: true });
    fs.writeFileSync(filePath, content);
  }
  if (stale.length > 0) {
    throw new Error(
      `Stale generated web plugin modules: ${stale.join(', ')}. Run pnpm build in doompi-web and commit them.`,
    );
  }
}

export interface SyncGeneratedModules {
  clientModulePath: string;
  cssModulePath: string;
  serverRegistry: string;
}

/**
 * The sync-time variant: renders the full plugin set (host built-ins plus the
 * installed composition's packages) into a generation directory the bundler
 * aliases over the committed builtin modules, plus the server-side registry
 * the hub loads at startup.
 */
export function writeSyncWebPluginModules(
  plugins: readonly DeclaredWebPlugin[],
  generatedDir: string,
): SyncGeneratedModules {
  fs.mkdirSync(generatedDir, { recursive: true });
  const clientModulePath = path.join(generatedDir, 'webPlugins.generated.ts');
  const cssModulePath = path.join(generatedDir, 'webPluginSources.generated.css');
  fs.writeFileSync(clientModulePath, renderClientModule(plugins, 'absolute'));
  fs.writeFileSync(cssModulePath, renderCssModule(plugins));
  return { clientModulePath, cssModulePath, serverRegistry: renderServerRegistry(plugins) };
}
