import { posix } from 'node:path';

import { GENERATED_DIR } from '../../constants/layout';
import type { ExtensionEntry, ExtensionGraph, ExtensionScope } from '../../types/extensionGraph';
import { toKebab } from '../identity';
import type { RenderOptions } from '../renderEntry/type';

/**
 * Renders the typed client a cockpit plugin calls its own API through.
 *
 * The two facts this injects are the two a package kept restating and getting
 * wrong: which scopes its API mounts at, and under which base path. Both are
 * read off the folder tree, so `api/file-edits/route.server.ts` at the session
 * scope is the whole declaration. A package that writes them out again is a
 * package that can disagree with itself, and several did.
 *
 * The route list is not read here. It is authored as plain data in
 * `src/types/apiRoutes.ts`, because this build evaluates no TypeScript and must
 * not learn how: it has no dependencies at all, and every specifier below is
 * emitted as text.
 */

const HEADER = '// Generated by @agimon-ai/doompi-build. Do not edit by hand.';

/** Server scopes cascade outward-in, the way the generated server entry mounts them. */
const SCOPE_ORDER: readonly ExtensionScope[] = ['global', 'workspace', 'session'];

/** One mount the tree declares: a base path, and the scopes it is reachable at. */
interface ClientMount {
  readonly basePath: string;
  readonly scopes: readonly ExtensionScope[];
  /** A valid identifier for the exported factory, when a package has several mounts. */
  readonly identifier: string;
}

function identifierFor(basePath: string, multiple: boolean): string {
  if (!multiple) return 'api';
  const camel = toKebab(basePath)
    .split('-')
    .filter((word) => word.length > 0)
    .map((word, index) => (index === 0 ? word : word[0]?.toUpperCase() + word.slice(1)))
    .join('');
  return /^[A-Za-z_]/u.test(camel) ? camel : `api${camel}`;
}

/**
 * The base path an api entry mounts at: the first literal segment below `api/`.
 *
 * An entry with no segment is the flat `api/route.server.ts` shape that predates
 * this convention. Its base path lives in a hand-written `DoomApi` the build
 * cannot read, so it contributes no client and keeps its hand-built URLs until
 * the folder is renamed.
 */
function baseSegmentOf(entry: ExtensionEntry): string | undefined {
  const first = entry.route[0];
  if (first === undefined || !('literal' in first)) return undefined;
  return first.literal;
}

function mountsOf(graph: ExtensionGraph): ClientMount[] {
  const scopesByBase = new Map<string, Set<ExtensionScope>>();
  for (const entry of graph.entries) {
    if (entry.side !== 'backend' || entry.surface !== 'api' || entry.role !== 'contribution') continue;
    const basePath = baseSegmentOf(entry);
    if (basePath === undefined) continue;
    const held = scopesByBase.get(basePath) ?? new Set<ExtensionScope>();
    held.add(entry.scope);
    scopesByBase.set(basePath, held);
  }

  const bases = [...scopesByBase.keys()].sort();
  return bases.map((basePath) => {
    const declared = scopesByBase.get(basePath) as Set<ExtensionScope>;
    // A facet mounts a contribution at its own scope and every scope below it,
    // so a global API answers workspace and session requests too.
    const shallowest = SCOPE_ORDER.findIndex((scope) => declared.has(scope));
    return {
      basePath,
      scopes: SCOPE_ORDER.slice(shallowest),
      identifier: identifierFor(basePath, bases.length > 1),
    };
  });
}

/** The extensionless relative specifier from the generated directory to the route table. */
function routesSpecifier(entryDir: string): string {
  const relative = posix.relative(entryDir, 'src/types/apiRoutes');
  return relative.startsWith('.') ? relative : `./${relative}`;
}

function renderMount(mount: ClientMount): string[] {
  const scopes = mount.scopes.map((scope) => `'${scope}'`).join(', ');
  const suffix = mount.identifier === 'api' ? '' : ` for the ${mount.basePath} mount`;
  return [
    `/** Scopes the tree mounts '${mount.basePath}' at${suffix}. */`,
    `export const ${mount.identifier}Scopes = [${scopes}] as const;`,
    '',
    `export const ${mount.identifier} = createApiClient(routes, {`,
    `  scopes: ${mount.identifier}Scopes,`,
    `  basePath: '${mount.basePath}',`,
    '  transport: (input, init) => sealedTransport.fetch(input, init),',
    '  sessionAddress: sessionApiAddress,',
    '});',
    '',
  ];
}

/**
 * The client source, or undefined when the tree declares no `api/<base-path>/`.
 *
 * `options.entryDir` is where the file will be written, so the relative import
 * of the route table is computed against it rather than assumed.
 */
export function renderApiClient(graph: ExtensionGraph, options: RenderOptions): string | undefined {
  const mounts = mountsOf(graph);
  if (mounts.length === 0) return undefined;

  const lines = [
    HEADER,
    "import { createApiClient, sessionApiAddress } from '@agimon-ai/doompi-core/web';",
    "import { sealedTransport } from '@agimon-ai/doompi-web-security/browser';",
    '',
    `import routes from '${routesSpecifier(options.entryDir ?? GENERATED_DIR)}';`,
    '',
    ...mounts.flatMap((mount) => renderMount(mount)),
  ];
  return `${lines.join('\n').replace(/\n+$/u, '')}\n`;
}
