import type { RuleDefinition } from '@agimon-ai/vibe-lint';

import {
  cleanImportPath,
  compatibilityWrapperOnly,
  cordisContextInPiAdapter,
  cordisFeaturePlugin,
  cordisHostOrder,
  cordisServiceInjection,
  doomCleanArchitectureBoundary,
  doomFolderLayout,
  doomLayerBoundary,
  doomServerFacetShape,
  flatServiceLayout,
  noAmbientHostAccess,
  noForwardingModule,
  packageLayerOrder,
  portsDeclaredInTypes,
  noInternalPublicImport,
  noLegacyCordisAccess,
  publicExportBoundary,
  schemaPlacement,
  serviceBoundary,
} from './architecture.js';
import { compositionLayout } from './compositionLayout.js';
import { doomConstants } from './constants.js';
import {
  disposeExternalSubscriptions,
  doomPackageShape,
  noDirectToolActivation,
  noLiveGlobalRegistry,
  noProtocolChannelLiterals,
  noRawPiEvents,
  noSameRunnerProtocol,
  piPeerVersion,
  preferCordisContainer,
  providerOwnedPolicy,
  thinPiAdapter,
} from './conventions.js';
import {
  doomExtensionSideBoundary,
  doomLegacySourceRoot,
  doomRoutedFileContract,
  doomRoutedFilePosition,
} from './extensionLayout.js';
import { neutralExtensionContracts } from './neutralContracts.js';
import { packageApiManifest } from './packageApi.js';
import { piExtensionDefaultFactory } from './piExtensionContract.js';
import { pluginCompositionWiring } from './pluginWiring.js';
import { doomPromptShape } from './prompts.js';
import { doomResourceKind } from './resourceKind.js';
import {
  webPluginEntry,
  webPluginGeneratedClientWiring,
  webPluginImportAllowlist,
  webPluginManifest,
  webPluginNoHandBuiltApiUrl,
  webPluginNoModuleState,
  webPluginProtocolLayout,
  webPluginTypedCalls,
} from './webPlugin.js';
import { webPluginToolRenderers } from './webPluginTools.js';

export const rules: Record<string, RuleDefinition> = {
  'composition-layout': compositionLayout,
  'routed-file-position': doomRoutedFilePosition,
  'routed-file-contract': doomRoutedFileContract,
  'extension-side-boundary': doomExtensionSideBoundary,
  'legacy-source-root': doomLegacySourceRoot,
  'plugin-composition-wiring': pluginCompositionWiring,
  'doom-constants': doomConstants,
  'neutral-extension-contracts': neutralExtensionContracts,
  'clean-import-path': cleanImportPath,
  'cordis-context-in-pi-adapter': cordisContextInPiAdapter,
  'cordis-feature-plugin': cordisFeaturePlugin,
  'cordis-host-order': cordisHostOrder,
  'cordis-service-injection': cordisServiceInjection,
  'doom-clean-architecture-boundary': doomCleanArchitectureBoundary,
  'doom-folder-layout': doomFolderLayout,
  'compatibility-wrapper-only': compatibilityWrapperOnly,
  'ports-declared-in-types': portsDeclaredInTypes,
  'public-export-boundary': publicExportBoundary,
  'flat-service-layout': flatServiceLayout,
  'no-ambient-host-access': noAmbientHostAccess,
  'no-forwarding-module': noForwardingModule,
  'no-internal-public-import': noInternalPublicImport,
  'no-legacy-cordis-access': noLegacyCordisAccess,
  'no-direct-tool-activation': noDirectToolActivation,
  'no-live-global-registry': noLiveGlobalRegistry,
  'package-layer-order': packageLayerOrder,
  'doom-layer-boundary': doomLayerBoundary,
  'doom-server-facet-shape': doomServerFacetShape,
  'service-boundary': serviceBoundary,
  'schema-placement': schemaPlacement,
  'doom-package-shape': doomPackageShape,
  'doom-prompt-shape': doomPromptShape,
  'doom-resource-kind': doomResourceKind,
  'pi-peer-version': piPeerVersion,
  'prefer-cordis-container': preferCordisContainer,
  'pi-extension-default-factory': piExtensionDefaultFactory,
  'thin-pi-adapter': thinPiAdapter,
  'no-raw-pi-events': noRawPiEvents,
  'no-same-runner-protocol': noSameRunnerProtocol,
  'no-protocol-channel-literals': noProtocolChannelLiterals,
  'dispose-external-subscriptions': disposeExternalSubscriptions,
  'provider-owned-policy': providerOwnedPolicy,
  'package-api-manifest': packageApiManifest,
  'web-plugin-entry': webPluginEntry,
  'web-plugin-generated-client-wiring': webPluginGeneratedClientWiring,
  'web-plugin-import-allowlist': webPluginImportAllowlist,
  'web-plugin-manifest': webPluginManifest,
  'web-plugin-no-hand-built-api-url': webPluginNoHandBuiltApiUrl,
  'web-plugin-no-module-state': webPluginNoModuleState,
  'web-plugin-protocol-layout': webPluginProtocolLayout,
  'web-plugin-typed-calls': webPluginTypedCalls,
  'web-plugin-tool-renderers': webPluginToolRenderers,
};
