import type { RuleDefinition } from '@agimon-ai/vibe-lint';
import {
  cleanImportPath,
  compatibilityWrapperOnly,
  cordisContextInPiAdapter,
  cordisFeaturePlugin,
  cordisHostOrder,
  cordisServiceInjection,
  doomCleanArchitectureBoundary,
  doomFolderLayout,
  doomLayerBoundary,
  flatServiceLayout,
  noAmbientHostAccess,
  noForwardingModule,
  packageLayerOrder,
  portsDeclaredInTypes,
  noInternalPublicImport,
  noLegacyCordisAccess,
  publicExportBoundary,
  schemaPlacement,
  serviceBoundary,
} from './architecture.js';
import {
  disposeExternalSubscriptions,
  doomPackageShape,
  noLiveGlobalRegistry,
  noProtocolChannelLiterals,
  noRawPiEvents,
  noSameRunnerProtocol,
  piPeerVersion,
  preferCordisContainer,
  providerOwnedPolicy,
  thinPiAdapter,
} from './conventions.js';
import { piExtensionDefaultFactory } from './piExtensionContract.js';
import { doomPromptShape } from './prompts.js';
import { webPluginEntry, webPluginImportAllowlist, webPluginManifest, webPluginNoModuleState } from './webPlugin.js';

export const rules: Record<string, RuleDefinition> = {
  'clean-import-path': cleanImportPath,
  'cordis-context-in-pi-adapter': cordisContextInPiAdapter,
  'cordis-feature-plugin': cordisFeaturePlugin,
  'cordis-host-order': cordisHostOrder,
  'cordis-service-injection': cordisServiceInjection,
  'doom-clean-architecture-boundary': doomCleanArchitectureBoundary,
  'doom-folder-layout': doomFolderLayout,
  'compatibility-wrapper-only': compatibilityWrapperOnly,
  'ports-declared-in-types': portsDeclaredInTypes,
  'public-export-boundary': publicExportBoundary,
  'flat-service-layout': flatServiceLayout,
  'no-ambient-host-access': noAmbientHostAccess,
  'no-forwarding-module': noForwardingModule,
  'no-internal-public-import': noInternalPublicImport,
  'no-legacy-cordis-access': noLegacyCordisAccess,
  'no-live-global-registry': noLiveGlobalRegistry,
  'package-layer-order': packageLayerOrder,
  'doom-layer-boundary': doomLayerBoundary,
  'service-boundary': serviceBoundary,
  'schema-placement': schemaPlacement,
  'doom-package-shape': doomPackageShape,
  'doom-prompt-shape': doomPromptShape,
  'pi-peer-version': piPeerVersion,
  'prefer-cordis-container': preferCordisContainer,
  'pi-extension-default-factory': piExtensionDefaultFactory,
  'thin-pi-adapter': thinPiAdapter,
  'no-raw-pi-events': noRawPiEvents,
  'no-same-runner-protocol': noSameRunnerProtocol,
  'no-protocol-channel-literals': noProtocolChannelLiterals,
  'dispose-external-subscriptions': disposeExternalSubscriptions,
  'provider-owned-policy': providerOwnedPolicy,
  'web-plugin-entry': webPluginEntry,
  'web-plugin-import-allowlist': webPluginImportAllowlist,
  'web-plugin-manifest': webPluginManifest,
  'web-plugin-no-module-state': webPluginNoModuleState,
};
