// Generated by @agimon-ai/doompi-build. Do not edit by hand.
import { definePiExtension } from '@agimon-ai/doompi-core/pi-extension';

import extra from './workspaces/sessions/(backend)/extra.cli';

type Factory<T> = (context: unknown) => T;
const at = <T>(value: T | Factory<T>, context: unknown): T =>
  typeof value === 'function' ? (value as Factory<T>)(context) : value;

export const extension = definePiExtension('@agimon-ai/doompi-grep', (context) => ({
  ...at(extra, context),
}));

export default extension;
