// Generated by @agimon-ai/doompi-build. Do not edit by hand.
import { definePiExtension, piToolContributions } from '@agimon-ai/doompi-core/pi-extension';

import toolGrep from './workspaces/sessions/(backend)/tool/grep.cli';

type Factory<T> = (context: unknown) => T;
const at = <T>(value: T | Factory<T>, context: unknown): T =>
  typeof value === 'function' ? (value as Factory<T>)(context) : value;
const via = <T>(identity: Record<string, unknown>, value: unknown): T => ({ ...identity, ...(value as object) }) as T;

export const extension = definePiExtension('@agimon-ai/doompi-grep', (context) => ({
  ...piToolContributions('@agimon-ai/doompi-grep', [via({ name: 'grep' }, at(toolGrep, context))]),
}));

export default extension;
