// Generated by @agimon-ai/doompi-build. Do not edit by hand.
import { defineServerPlugin } from '@agimon-ai/doompi-core/server-facet';

import toolGrep from './workspaces/sessions/(backend)/tool/grep.server';

type Factory<T> = (context: unknown) => T;
const at = <T>(value: T | Factory<T>, context: unknown): T =>
  typeof value === 'function' ? (value as Factory<T>)(context) : value;
const via = <T>(identity: Record<string, unknown>, value: unknown): T => ({ ...identity, ...(value as object) }) as T;

export const facet = defineServerPlugin({
  name: '@agimon-ai/doompi-grep',
  session: (context) => ({
    tools: [via({ name: 'grep' }, at(toolGrep, context))],
  }),
});

export default facet;
