// Generated by @agimon-ai/doompi-build. Do not edit by hand.
import { defineWebPlugin } from '@agimon-ai/doompi-core/web';

import toolGrep from './workspaces/sessions/(frontend)/tool/grep';

type Factory<T> = (context: unknown) => T;
const at = <T>(value: T | Factory<T>, context: unknown): T =>
  typeof value === 'function' ? (value as Factory<T>)(context) : value;
const via = <T>(identity: Record<string, unknown>, value: unknown): T => ({ ...identity, ...(value as object) }) as T;

export const webPlugin = defineWebPlugin({
  id: 'grep',
  session: {
    toolRenderers: [via({ tools: ['grep'] }, at(toolGrep, undefined))],
  },
});
