import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import {
  type DeclaredPackageApi,
  DOOM_API_SCOPES,
  type DoomApiScope,
  declaredApisOf,
  DoomApiManifestError,
  orderDeclaredApis,
} from '@agimon-ai/doompi-extension-contracts/package-api';

const API_DIRECTORY = ['.doompi', 'api'];
const CURRENT_DIRECTORY = 'current';
const HEADER = '// Generated by doompi sync. Do not edit by hand.';

export interface ApiRoutesSyncInput {
  /** Resolved extension entry paths from the sync state; package roots derive from them. */
  resolvedEntries: Record<string, string>;
  homeDirectory?: string;
  onNotice?: (message: string) => void;
}

export interface ApiRoutesSyncResult {
  directory: string;
  /** Base paths written per scope, so sync can report what a host will mount. */
  mounted: Record<DoomApiScope, string[]>;
}

/** Walks from a resolved module path up to the directory owning its package.json. */
function packageRootOf(entryPath: string): string | undefined {
  let dir = path.dirname(entryPath);
  for (;;) {
    if (fs.existsSync(path.join(dir, 'package.json'))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) return undefined;
    dir = parent;
  }
}

function camel(basePath: string): string {
  return basePath.replace(/-([a-z0-9])/gu, (_, character: string) => character.toUpperCase());
}

/**
 * One scope's module: an import per package that declares that scope, and the
 * list a host mounts. Absolute file URLs, because the host process runs from
 * somewhere else entirely and the packages live wherever the composition
 * installed them.
 */
function renderModule(scope: DoomApiScope, apis: readonly DeclaredPackageApi[]): string {
  const lines = [HEADER];
  const names: string[] = [];
  for (const api of apis) {
    const entry = api[scope];
    if (entry === undefined) continue;
    const name = `${camel(api.basePath)}Api`;
    names.push(name);
    const specifier = pathToFileURL(path.join(api.packageDir, entry.dist ?? entry.entry)).href;
    lines.push(`import { api as ${name} } from '${specifier}';`);
  }
  lines.push('', `export const apis = [${names.join(', ')}];`, '');
  return lines.join('\n');
}

/**
 * The API phase of `doompi sync`: write the route modules each host imports.
 *
 * Packages are discovered from doompiApi manifests in the resolved composition;
 * nothing here names a package. The two modules are published machine-wide at
 * ~/.doompi/api/current, and the swap is a rename so a starting session server
 * never imports a half-written module. A package whose block is malformed is a
 * notice and is left out, never a failed sync.
 */
export function syncApiRoutes(input: ApiRoutesSyncInput): ApiRoutesSyncResult {
  const homeDirectory = input.homeDirectory ?? os.homedir();
  const notice = input.onNotice ?? ((): void => {});
  const roots = [
    ...new Set(
      Object.values(input.resolvedEntries)
        .map(packageRootOf)
        .filter((root): root is string => root !== undefined),
    ),
  ].sort();

  const declared: DeclaredPackageApi[] = [];
  for (const root of roots) {
    let manifest: Record<string, unknown>;
    try {
      manifest = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')) as Record<string, unknown>;
    } catch (error) {
      notice(`package.json in ${root} is unreadable (${String(error)}); its API is skipped`);
      continue;
    }
    try {
      declared.push(...declaredApisOf(root, manifest));
    } catch (error) {
      notice(error instanceof DoomApiManifestError ? error.message : String(error));
    }
  }
  const ordered = orderDeclaredApis(declared, notice);

  const apiRoot = path.join(homeDirectory, ...API_DIRECTORY);
  const staging = path.join(apiRoot, `next-${String(process.pid)}`);
  fs.rmSync(staging, { recursive: true, force: true });
  fs.mkdirSync(staging, { recursive: true });
  const mounted = { session: [] as string[], hub: [] as string[] };
  for (const scope of DOOM_API_SCOPES) {
    fs.writeFileSync(path.join(staging, `${scope}.routes.mjs`), renderModule(scope, ordered));
    mounted[scope] = ordered.filter((api) => api[scope] !== undefined).map((api) => api.basePath);
  }
  const current = path.join(apiRoot, CURRENT_DIRECTORY);
  fs.rmSync(current, { recursive: true, force: true });
  fs.renameSync(staging, current);
  return { directory: current, mounted };
}
