import fs from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
import {
  type DeclaredPackageApi,
  DOOM_API_SCOPES,
  type DoomApiScope,
  declaredApisOf,
  DoomApiManifestError,
  orderDeclaredApis,
} from '@agimon-ai/doompi-extension-contracts/package-api';
import {
  type DeclaredServerFacet,
  declaredServerFacetsOf,
  DoomServerFacetManifestError,
  orderServerFacets,
} from '@agimon-ai/doompi-extension-contracts/server-facet';

const HEADER = '// Generated by doompi sync. Do not edit by hand.';

/** The route module a host loads for one scope, named the same by producer and consumer. */
export function apiRoutesFile(scope: DoomApiScope): string {
  return `${scope}.routes.mjs`;
}

/** The server facet module a host loads for one scope. */
export function serverFacetsFile(scope: DoomApiScope): string {
  return `${scope}.facets.mjs`;
}

export interface ApiRoutesSyncInput {
  /** Resolved extension entry paths from the sync state; package roots derive from them. */
  resolvedEntries: Record<string, string>;
  /** Immutable generation directory that receives the generated route modules. */
  outputDirectory: string;
  onNotice?: (message: string) => void;
}

export interface ApiRoutesSyncResult {
  directory: string;
  /** Base paths written per scope, so sync can report what a host will mount. */
  mounted: Record<DoomApiScope, string[]>;
  /** Package names written per scope, so sync can report what a host will install. */
  facets: Record<DoomApiScope, string[]>;
}

/** Walks from a resolved module path up to the directory owning its package.json. */
function packageRootOf(entryPath: string): string | undefined {
  let dir = path.dirname(entryPath);
  for (;;) {
    if (fs.existsSync(path.join(dir, 'package.json'))) return dir;
    const parent = path.dirname(dir);
    if (parent === dir) return undefined;
    dir = parent;
  }
}

function camel(basePath: string): string {
  return basePath.replace(/-([a-z0-9])/gu, (_, character: string) => character.toUpperCase());
}

/**
 * One scope's module: an import per package that declares that scope, and the
 * list a host mounts. Absolute file URLs, because the host process runs from
 * somewhere else entirely and the packages live wherever the composition
 * installed them.
 */
function renderModule(scope: DoomApiScope, apis: readonly DeclaredPackageApi[]): string {
  const lines = [HEADER];
  const names: string[] = [];
  for (const api of apis) {
    const entry = api[scope];
    if (entry === undefined) continue;
    const name = `${camel(api.basePath)}Api`;
    names.push(name);
    const specifier = pathToFileURL(path.join(api.packageDir, entry.dist ?? entry.entry)).href;
    lines.push(`import { api as ${name} } from '${specifier}';`);
  }
  lines.push('', `export const apis = [${names.join(', ')}];`, '');
  return lines.join('\n');
}

/**
 * One scope's facet module. Same shape as the route module and for the same
 * reason: absolute file URLs, because the host process runs somewhere else
 * entirely. A facet declaring no interest in this scope is left out here
 * rather than checked for at install time.
 */
function renderFacetModule(scope: DoomApiScope, facets: readonly DeclaredServerFacet[]): string {
  const lines = [HEADER];
  const names: string[] = [];
  facets.forEach((facet, index) => {
    if (!facet.scopes.includes(scope)) return;
    const name = `facet${index}`;
    names.push(name);
    const specifier = pathToFileURL(path.join(facet.packageDir, facet.dist)).href;
    lines.push(`import ${name} from '${specifier}';`);
  });
  lines.push('', `export const facets = [${names.join(', ')}];`, '');
  return lines.join('\n');
}

/** Writes the API and facet modules for both scopes inside an unpublished sync generation. */
export function syncApiRoutes(input: ApiRoutesSyncInput): ApiRoutesSyncResult {
  const notice = input.onNotice ?? ((): void => {});
  const roots = [
    ...new Set(
      Object.values(input.resolvedEntries)
        .map(packageRootOf)
        .filter((root): root is string => root !== undefined),
    ),
  ].sort();

  const declared: DeclaredPackageApi[] = [];
  const facetsDeclared: DeclaredServerFacet[] = [];
  for (const root of roots) {
    let manifest: Record<string, unknown>;
    try {
      manifest = JSON.parse(fs.readFileSync(path.join(root, 'package.json'), 'utf8')) as Record<string, unknown>;
    } catch (error) {
      notice(`package.json in ${root} is unreadable (${String(error)}); its API is skipped`);
      continue;
    }
    try {
      declared.push(...declaredApisOf(root, manifest));
    } catch (error) {
      notice(error instanceof DoomApiManifestError ? error.message : String(error));
    }
    try {
      facetsDeclared.push(...declaredServerFacetsOf(root, manifest));
    } catch (error) {
      notice(error instanceof DoomServerFacetManifestError ? error.message : String(error));
    }
  }
  const ordered = orderDeclaredApis(declared, notice);
  const orderedFacets = orderServerFacets(facetsDeclared, notice);

  fs.rmSync(input.outputDirectory, { recursive: true, force: true });
  fs.mkdirSync(input.outputDirectory, { recursive: true });
  const mounted = { session: [] as string[], hub: [] as string[] };
  const facets = { session: [] as string[], hub: [] as string[] };
  for (const scope of DOOM_API_SCOPES) {
    fs.writeFileSync(path.join(input.outputDirectory, `${scope}.routes.mjs`), renderModule(scope, ordered));
    mounted[scope] = ordered.filter((api) => api[scope] !== undefined).map((api) => api.basePath);
    fs.writeFileSync(path.join(input.outputDirectory, `${scope}.facets.mjs`), renderFacetModule(scope, orderedFacets));
    facets[scope] = orderedFacets.filter((facet) => facet.scopes.includes(scope)).map((facet) => facet.packageName);
  }
  return { directory: input.outputDirectory, mounted, facets };
}
