// Generated by src/adapters/webPluginGenerate.ts. Do not edit by hand.
import type { WebPluginDefinition } from '@agimon-ai/doompi-web-contracts';

export const webPlugins: readonly WebPluginDefinition[] = [];
