import { posix } from 'node:path';

import type { ExtensionEntry, ExtensionScope } from '../../types/extensionGraph';
import { type Identity, renderIdentity, toKebab, toSnake } from '../identity';
import type { BuildTarget, ResolvedContribution, TargetResolution } from '../resolveTarget/type';
import type { RenderOptions } from './type';

const HEADER = '// Generated by @agimon-ai/doompi-build. Do not edit by hand.';

/** The one field that is a record keyed by event name rather than an array. */
const RECORD_FIELDS: readonly string[] = ['events'];
/** Fields that accept one declaration rather than an array of declarations. */
const SINGLETON_FIELDS: readonly string[] = ['start'];

/**
 * Fields whose members are factories rather than declarations.
 *
 * Keyed by target, not by field name alone, because `channels` means two
 * different things. A server facet's array holds `() => DoomHubChannel`, so
 * the host can build one per mount. The cockpit's holds the contribution
 * itself. Treating them alike called a plain object as a function.
 */
const FACTORY_FIELDS: Readonly<Record<BuildTarget, readonly string[]>> = {
  cli: ['channels'],
  server: ['channels'],
  web: [],
};

/**
 * Fields whose member is always a factory of the value, never the value.
 *
 * A Cordis plugin is itself a function, so nothing at runtime separates one
 * from a `(context) => plugin` factory. Rather than guess, the service surface
 * is uniformly a factory and is always called. That is also what lets a
 * package with shared per-mount state decompose: the service builds the graph
 * from the mount and publishes it, and every other contribution is a getter,
 * so it is built after the service fibers are up and can inject it.
 */
const ALWAYS_FACTORY_FIELDS: readonly string[] = ['services'];

const SCOPE_ORDER: readonly ExtensionScope[] = ['global', 'workspace', 'session'];

/**
 * Resolves a routed file's default export, which may be the declaration or a
 * factory of one. Both host helpers already accept either shape, so a
 * generated entry has to as well. Emitted rather than imported, so a generated
 * entry carries no runtime dependency beyond the helper it is calling.
 */
/** The contribution set each host reads, used to annotate the emitted getters. */
const CONTRIBUTIONS_TYPE: Readonly<Record<BuildTarget, string>> = {
  cli: 'PiPluginContributions',
  server: 'DoomServerSessionPlugin',
  web: 'WebPluginContributions',
};

/**
 * Resolves a routed file's default export without imposing one host context on
 * every factory. The generated mount supplies the concrete context, and `at`
 * preserves that type while still accepting declaration objects.
 */
function resolver(): string {
  return [
    'type Factory<T, C> = (context: C) => T;',
    'const at = <T, C>(value: T | Factory<T, C>, context: C): T =>',
    "  typeof value === 'function' ? (value as Factory<T, C>)(context) : value;",
  ].join('\n');
}

/**
 * Applies the identity the path derived, letting the authored value win.
 *
 * A call rather than an object literal on purpose. `{ name: 'x', ...value }`
 * is what this means, but TypeScript reports TS2783 whenever the spread's type
 * also declares the key, which is the common case here.
 *
 * The parameters are deliberately untyped so `T` is inferred from the
 * contribution array this sits in rather than from either argument: the
 * authored file supplies only the half the path cannot. The cost is that the
 * merged shape is not checked against `T`, only its position is.
 */
// One line on purpose: at 118 characters it fits the repository's 120 print
// width, so oxfmt would join a wrapped form and leave every build dirty.
const IDENTITY_HELPER =
  'const via = <T>(identity: Record<string, unknown>, value: unknown): T => ({ ...identity, ...(value as object) }) as T;';

/**
 * Every fill is a slot fill. There is no host-region special case.
 *
 * The cockpit's own regions are slots like any other: an activity section
 * already renders into `activity.<group>`, which is why naming the target
 * directly works for a host region and a plugin's slot alike. Keeping this
 * uniform is what lets a layout package declare new regions without the build
 * tooling learning about them.
 */
function fillIdentity(name: string, target: string | undefined): Identity {
  if (target === undefined) return { id: toKebab(name) };
  return { slot: target, id: toKebab(name) };
}

/** What the path can tell each host, keyed by the folder the author typed. */
const BACKEND_IDENTITY: Readonly<Record<string, (name: string) => Identity>> = {
  tool: (name) => ({ name: toSnake(name) }),
  // Kebab, unlike a tool. A command name is what the user types after the
  // slash and it reaches registerCommand verbatim, so `subagents-doctor` must
  // stay `/subagents-doctor` rather than becoming `/subagents_doctor`.
  command: (name) => ({ name: toKebab(name) }),
  channel: (name) => ({ frameType: toSnake(name) }),
  // Only the server reads this; the CLI keys its events record by the same name.
  hook: (name) => ({ event: toSnake(name) }),
  mode: (name) => ({ name: toKebab(name) }),
};

const FRONTEND_IDENTITY: Readonly<Record<string, (name: string, options: RenderOptions) => Identity>> = {
  tool: (name) => ({ tools: [toSnake(name)] }),
  channel: (name) => ({ channel: toSnake(name) }),
  slot: (name, options) => ({ slot: `${options.pluginId}.${toKebab(name)}` }),
  command: (name) => ({ id: toKebab(name) }),
  tab: (name) => ({ id: toKebab(name) }),
  dock: (name) => ({ id: toKebab(name) }),
  setting: (name) => ({ id: toKebab(name) }),
  action: (name) => ({ id: toKebab(name) }),
  mode: (name) => ({ name: toKebab(name) }),
  'activity-group': (name) => ({ name: toKebab(name) }),
  // A leader binding's id is namespaced like a slot, because the key tree is
  // shared and two plugins must not collide on one path's identity.
  leader: (name, options) => ({ id: `${options.pluginId}.${toKebab(name)}` }),
};

/**
 * What the path knows about a contribution's identity.
 *
 * Keyed by surface, because the folder is what the author types. A surface
 * absent from the table, or an identity the path cannot supply such as a tab's
 * human label, is left entirely to the authored file.
 */
function identityFor(
  contribution: ResolvedContribution,
  target: BuildTarget,
  options: RenderOptions,
): Identity | undefined {
  const { entry } = contribution;
  const surface = entry.surface;
  if (surface === undefined) return undefined;

  if (target !== 'web') return BACKEND_IDENTITY[surface]?.(entry.name);
  if (surface === 'fill') return fillIdentity(entry.name, entry.target);
  return FRONTEND_IDENTITY[surface]?.(entry.name, options);
}

/** A stable, unique, valid identifier built from path words. */
function uniqueIdentifier(parts: readonly string[], taken: Set<string>): string {
  const words = parts
    .join('-')
    .split(/[^A-Za-z0-9]+/u)
    .filter((word) => word.length > 0);
  const head = words.map((word, index) => (index === 0 ? word : word[0]?.toUpperCase() + word.slice(1))).join('');
  const base = /^[A-Za-z_]/u.test(head) ? head : `x${head}`;
  let candidate = base;
  let suffix = 2;
  while (taken.has(candidate)) candidate = `${base}${suffix++}`;
  taken.add(candidate);
  return candidate;
}

/** A stable, unique, valid identifier: surface and name, disambiguated by scope when needed. */
function identifierFor(contribution: ResolvedContribution, taken: Set<string>): string {
  return uniqueIdentifier([contribution.entry.surface ?? 'extra', contribution.entry.name], taken);
}

/** The extensionless relative specifier from a generated entry to a routed file. */
function specifierFor(file: string, entryDir: string): string {
  const target = file.replace(/\.[^.]+$/u, '');
  const relative = posix.relative(entryDir, target);
  return relative.startsWith('.') ? relative : `./${relative}`;
}

interface Binding {
  readonly identifier: string;
  readonly contribution: ResolvedContribution;
  readonly identity: Identity | undefined;
  /** The paired presentation file, when one is folded into this contribution. */
  readonly renderers: { readonly identifier: string; readonly file: string } | undefined;
}

function bind(resolution: TargetResolution, options: RenderOptions): Binding[] {
  const taken = new Set<string>();
  return [...resolution.contributions]
    .sort((left, right) => left.entry.file.localeCompare(right.entry.file))
    .map((contribution) => {
      // The contribution takes its identifier first, so the plain name stays
      // with the tool rather than going to whichever file sorted earlier.
      const identifier = identifierFor(contribution, taken);
      const paired = contribution.renderers;
      return {
        identifier,
        contribution,
        identity: identityFor(contribution, resolution.target, options),
        renderers:
          paired === undefined
            ? undefined
            : { identifier: uniqueIdentifier(['render', paired.name], taken), file: paired.file },
      };
    });
}

/** Scope nesting depth, so a contribution can find the root that encloses it. */
const DEPTH: Readonly<Record<ExtensionScope, number>> = { global: 0, workspace: 1, session: 2 };

interface RootBinding {
  /** The imported factory. */
  readonly identifier: string;
  /** The declaration it returned: `value` plus this scope's lifecycle hooks. */
  readonly declaration: string;
  /** The mount context contributions beneath this root receive. */
  readonly context: string;
  readonly entry: ExtensionEntry;
}

function rootBindings(entries: readonly ExtensionEntry[]): RootBinding[] {
  return entries.map((entry) => {
    const suffix = entry.scope[0]?.toUpperCase() + entry.scope.slice(1);
    return { identifier: `root${suffix}`, declaration: `scope${suffix}`, context: `context${suffix}`, entry };
  });
}

/**
 * Constructs each scope before anything it contains, outermost first.
 *
 * Every root is handed the context its enclosing root produced. Root factories
 * may be async, so the generated host factory awaits each one before exposing
 * its value to narrower contributions.
 */
function rootPrologue(roots: readonly RootBinding[], base: string): string[] {
  const lines: string[] = [];
  let enclosing = base;
  for (const root of roots) {
    lines.push(`const ${root.declaration} = await ${root.identifier}(${enclosing});`);
    lines.push(`const ${root.context} = { ...${enclosing}, root: ${root.declaration}.value };`);
    enclosing = root.context;
  }
  return lines;
}

/** The context a contribution sees: the nearest enclosing root's, or the mount's. */
function contextForScope(roots: readonly RootBinding[], scope: ExtensionScope, base: string): string {
  let found = base;
  for (const root of roots) {
    if (DEPTH[root.entry.scope] <= DEPTH[scope]) found = root.context;
  }
  return found;
}

function hatchBindings(entries: readonly ExtensionEntry[]): { identifier: string; entry: ExtensionEntry }[] {
  return [...entries]
    .sort((left, right) => left.file.localeCompare(right.file))
    .map((entry, index) => ({ identifier: `extra${index === 0 ? '' : index + 1}`, entry }));
}

/**
 * One contribution as it appears inside its array, identity first so the file wins.
 *
 * The browser half is never resolved. The cockpit builds its definition as
 * data and starts it separately, so a frontend file has no mount context to
 * receive, and resolving anyway would call any export that happens to be a
 * function. A React component is a function, so that is not hypothetical.
 */
function member(binding: Binding, contextExpression: string, target: BuildTarget): string {
  if (ALWAYS_FACTORY_FIELDS.includes(binding.contribution.field)) {
    return `${binding.identifier}(${contextExpression})`;
  }

  const base = target === 'web' ? binding.identifier : `at(${binding.identifier}, ${contextExpression})`;
  // Pi command tuples already carry their native name and handler. A path
  // identity spread would turn the tuple into an object and lose both.
  if (
    target === 'cli' &&
    binding.contribution.entry.surface === 'command' &&
    binding.contribution.entry.platform === 'cli'
  )
    return base;
  // A terminal tool renderer is a field of the tool declaration, not a
  // registration of its own, so the pair is merged at runtime: three tool
  // shapes reach this array and each holds renderers somewhere different.
  const resolved =
    binding.renderers === undefined
      ? base
      : `withPiRenderers(${base}, at(${binding.renderers.identifier}, ${contextExpression}))`;
  const isFactory = FACTORY_FIELDS[target].includes(binding.contribution.field);
  if (binding.identity === undefined) return isFactory ? binding.identifier : resolved;

  const identity = renderIdentity(binding.identity);
  // A channel array holds factories, so the identity is applied inside one.
  if (isFactory) return `() => via({ ${identity} }, ${binding.identifier}())`;
  return `via({ ${identity} }, ${resolved})`;
}

/**
 * The CLI keeps replacements apart from additions, and only the value knows
 * which a tool is. A tool that claims a name Pi already ships is an override
 * claim the host arbitrates, not a second registration, but both are authored
 * in `tool/`, so the path cannot tell them apart. The generated entry defers
 * to a runtime split instead.
 */
function wrapField(field: string, target: BuildTarget, rendered: string, options: RenderOptions): string {
  if (field !== 'tools' || target !== 'cli') return `${field}: ${rendered},`;
  return `...piToolContributions('${options.packageName}', ${rendered}),`;
}

/** The server entry imports only the types its scopes actually use. */
function serverImport(scopes: readonly string[]): string {
  const types = scopes.some((line) => line.includes('get ')) ? ['type DoomServerSessionPlugin'] : [];
  return `import { ${['defineServerPlugin', ...types].join(', ')} } from '@agimon-ai/doompi-core/server-facet';`;
}

/** The CLI entry imports only what its body and inferred options use. */
function cliImport(body: readonly string[], infersOptions: boolean): string {
  const named = ['definePiExtension'];
  if (body.some((line) => line.includes('piToolContributions('))) named.push('piToolContributions');
  if (body.some((line) => line.includes('withPiRenderers('))) named.push('withPiRenderers');
  const types = [
    ...(body.some((line) => line.includes('at(')) || infersOptions ? ['type PiPluginContext'] : []),
    ...(body.some((line) => line.includes('get ')) ? ['type PiPluginContributions'] : []),
  ];
  return `import { ${[...named, ...types].join(', ')} } from '@agimon-ai/doompi-core/pi-extension';`;
}

/**
 * Emits a contribution as a getter, so it is built after services mount.
 *
 * Both host helpers register `services` first and read every other field
 * afterwards. A plain property would be evaluated when the entry's factory
 * returns, which is before any service exists, so a routed file could never
 * inject one at construction and every package with shared per-mount state
 * would be stuck in one closure.
 *
 * `services` itself stays a plain property: it is what the helper reads first,
 * and a getter for it would buy nothing.
 */
function defer(field: string, rendered: string, target: BuildTarget): string {
  if (field === 'services' || rendered.startsWith('...')) return rendered;
  const [name, ...value] = rendered.split(': ');
  // Annotated, because a getter gets no contextual type from the object
  // literal it sits in, so the identity helper's T would widen to unknown and
  // the contribution would stop type checking against the array it joins.
  const type = `${CONTRIBUTIONS_TYPE[target]}['${name}']`;
  return `get ${name}(): ${type} { return ${value.join(': ').replace(/,$/u, '')}; },`;
}

/**
 * The contributions object's body.
 *
 * The mount context is resolved per contribution rather than once, because a
 * root rebinds it for everything beneath it and two contributions at different
 * scopes can therefore see different contexts in the same object.
 */
function bodyFor(
  bindings: readonly Binding[],
  indent: string,
  contextOf: (binding: Binding) => string,
  target: BuildTarget,
  options: RenderOptions,
): string[] {
  const grouped = new Map<string, Binding[]>();
  for (const binding of bindings) {
    const held = grouped.get(binding.contribution.field);
    if (held === undefined) grouped.set(binding.contribution.field, [binding]);
    else held.push(binding);
  }

  const lines: string[] = [];
  for (const field of [...grouped.keys()].sort()) {
    const members = grouped.get(field) as Binding[];
    if (RECORD_FIELDS.includes(field)) {
      lines.push(`${indent}${field}: {`);
      for (const entry of members) {
        lines.push(
          `${indent}  ${toSnake(entry.contribution.entry.name)}: at(${entry.identifier}, ${contextOf(entry)}),`,
        );
      }
      lines.push(`${indent}},`);
      continue;
    }
    if (SINGLETON_FIELDS.includes(field)) {
      const entry = members[0];
      if (entry) {
        const rendered = member(entry, contextOf(entry), target);
        lines.push(`${indent}${defer(field, `${field}: ${rendered},`, target)}`);
      }
      continue;
    }
    const rendered = `[${members.map((entry) => member(entry, contextOf(entry), target)).join(', ')}]`;
    lines.push(`${indent}${defer(field, wrapField(field, target, rendered, options), target)}`);
  }
  return lines;
}

/** Root-owned registrations join routed registrations in the host's usual fields. */
function withRootRegistrations(
  body: readonly string[],
  roots: readonly RootBinding[],
  target: 'cli' | 'server',
  indent: string,
  scope: ExtensionScope,
): string[] {
  if (roots.length === 0) return [...body];
  const lines = [...body];
  const servicesIndex = lines.findIndex((line) => line.startsWith(`${indent}services: [`));
  const routedServices =
    servicesIndex < 0 ? '' : (lines.splice(servicesIndex, 1)[0]?.match(/services: \[(.*)\],$/u)?.[1] ?? '');
  const services = [...roots.map((root) => `...(${root.declaration}.services ?? [])`), routedServices]
    .filter(Boolean)
    .join(', ');
  lines.push(`${indent}services: [${services}],`);

  if (target === 'server' && scope === 'session') {
    const activitiesIndex = lines.findIndex((line) => line.startsWith(`${indent}get activities()`));
    const routedActivities =
      activitiesIndex < 0 ? '' : (lines.splice(activitiesIndex, 1)[0]?.match(/return \[(.*)\]; \},$/u)?.[1] ?? '');
    const activities = [...roots.map((root) => `...(${root.declaration}.activities ?? [])`), routedActivities]
      .filter(Boolean)
      .join(', ');
    lines.push(`${indent}get activities(): DoomServerSessionPlugin['activities'] { return [${activities}]; },`);
  }
  return lines;
}

function importsFor(
  bindings: readonly Binding[],
  hatches: readonly { identifier: string; entry: ExtensionEntry }[],
  roots: readonly RootBinding[],
  entryDir: string,
): string[] {
  return [
    ...roots.map((r) => `import ${r.identifier} from '${specifierFor(r.entry.file, entryDir)}';`),
    ...bindings.flatMap((b) => [
      `import ${b.identifier} from '${specifierFor(b.contribution.entry.file, entryDir)}';`,
      ...(b.renderers === undefined
        ? []
        : [`import ${b.renderers.identifier} from '${specifierFor(b.renderers.file, entryDir)}';`]),
    ]),
    ...hatches.map((h) => `import ${h.identifier} from '${specifierFor(h.entry.file, entryDir)}';`),
  ];
}

function compact(lines: readonly string[]): string {
  return lines.filter((line, index, all) => !(line === '' && all[index - 1] === '')).join('\n');
}

/** Infers the public Pi options contract from authored context factories. */
function cliOptionsType(identifiers: readonly string[]): string[] {
  if (identifiers.length === 0) return [];
  const members = identifiers.map((identifier) => `OptionsOf<typeof ${identifier}>`).join(' | ');
  return [
    'type OptionsOf<T> = T extends (context: PiPluginContext<infer Options>) => unknown ? Options : never;',
    `type InferredOptions = Exclude<${members}, undefined>;`,
    'type Intersect<Union> =',
    '  (Union extends unknown ? (value: Union) => void : never) extends (value: infer Value) => void ? Value : never;',
    'type ExtensionOptions = [InferredOptions] extends [never] ? undefined : Intersect<InferredOptions>;',
    '',
  ];
}

/**
 * Emits the resolver only when something calls it.
 *
 * Extension packages compile with noUnusedLocals, so a generated entry whose
 * every contribution is a factory would otherwise fail to typecheck on an
 * unused helper.
 */
function resolverFor(body: readonly string[]): string[] {
  const lines: string[] = [];
  if (body.some((line) => line.includes('at('))) lines.push(resolver());
  if (body.some((line) => line.includes('via('))) lines.push(IDENTITY_HELPER);
  return lines.length > 0 ? [...lines, ''] : [];
}

/** `noUnusedParameters` means a scope that never threads context takes none. */
function parameterFor(lines: readonly string[]): string {
  return lines.some((line) => line.includes(', context)') || line.includes('(context)')) ? '(context)' : '()';
}

/**
 * The scope's factory: an expression body, or a block when roots come first.
 *
 * A root has to be constructed before the object that reads it, so a scope
 * that has one becomes statements followed by a return rather than a bare
 * object literal.
 */
function scopeBody(
  prologue: readonly string[],
  hooks: string | undefined,
  body: readonly string[],
  indent: string,
): string[] {
  const object = [...(hooks === undefined ? [] : [`${indent}  ${hooks}`]), ...body];
  const asynchronous = [...prologue, ...body].some((line) => line.includes('await '));
  const prefix = asynchronous ? 'async ' : '';
  if (prologue.length === 0) return [`${prefix}${parameterFor(body)} => ({`, ...object, `${indent}}),`];
  return [
    `${prefix}${parameterFor([...prologue, ...body])} => {`,
    ...prologue.map((line) => `${indent}  ${line}`),
    `${indent}  return {`,
    ...object.map((line) => `  ${line}`),
    `${indent}  };`,
    `${indent}},`,
  ];
}

/** Folds every enclosing root's lifecycle hooks into the one set the host reads. */
function rootHooks(roots: readonly RootBinding[]): string | undefined {
  if (roots.length === 0) return undefined;
  return `...composeRootHooks(${roots.map((root) => root.declaration).join(', ')}),`;
}

/** The interactive terminal entry. One mount, so every backend contribution lands in it. */
export function renderCliEntry(resolution: TargetResolution, options: RenderOptions): string {
  const bindings = bind(resolution, options);
  const hatches = hatchBindings(resolution.escapeHatches);
  // One mount, so every root in the tree applies, whatever its scope.
  const roots = rootBindings(resolution.roots);
  const prologue = rootPrologue(roots, 'context');
  const innermost = roots[roots.length - 1]?.context ?? 'context';
  const body = [
    ...withRootRegistrations(
      bodyFor(bindings, '  ', (b) => contextForScope(roots, b.contribution.entry.scope, 'context'), 'cli', options),
      roots,
      'cli',
      '  ',
      'session',
    ),
    ...hatches.map((hatch) => `  ...await at(${hatch.identifier}, ${innermost}),`),
  ];
  const factory = scopeBody(prologue, rootHooks(roots), body, '');
  const optionIdentifiers = [
    ...roots.map((root) => root.identifier),
    ...bindings.map((binding) => binding.identifier),
    ...hatches.map((hatch) => hatch.identifier),
  ];
  const infersOptions = optionIdentifiers.length > 0;

  return compact([
    HEADER,
    cliImport([...prologue, ...body], infersOptions),
    ...(roots.length > 0 ? ["import { composeRootHooks } from '@agimon-ai/doompi-core/extension-file';"] : []),
    '',
    ...importsFor(bindings, hatches, roots, options.entryDir),
    '',
    ...cliOptionsType(optionIdentifiers),
    ...resolverFor(body),
    `export const extension = definePiExtension${infersOptions ? '<ExtensionOptions>' : ''}('${options.packageName}', ${factory[0]}`,
    ...factory.slice(1, -1),
    `${factory[factory.length - 1]?.replace(/,$/u, '')});`,
    '',
    'export default extension;',
    '',
  ]);
}

/**
 * The headless entry, one declaration per scope.
 *
 * Contributions cascade downward here because the server does not do it
 * itself: a facet reads exactly one `plugin[host.scope]` and nothing from the
 * scopes above it. Emitting the repetition is what lets an author declare a
 * channel once and have it mount at all three scopes.
 */
export function renderServerEntry(resolution: TargetResolution, options: RenderOptions): string {
  const bindings = bind(resolution, options);
  const hatches = hatchBindings(resolution.escapeHatches);
  const allRoots = rootBindings(resolution.roots);

  const scopes: string[] = [];
  let usesRoots = false;
  for (const [index, scope] of SCOPE_ORDER.entries()) {
    const visible = bindings.filter((b) => SCOPE_ORDER.indexOf(b.contribution.entry.scope) <= index);
    const here = hatches.filter((h) => SCOPE_ORDER.indexOf(h.entry.scope) <= index);
    // Each scope is an independent mount, so it constructs the roots that
    // enclose it from scratch rather than sharing the deeper scope's.
    const roots = allRoots.filter((root) => SCOPE_ORDER.indexOf(root.entry.scope) <= index);
    const innermost = roots[roots.length - 1]?.context ?? 'context';
    const body = [
      ...withRootRegistrations(
        bodyFor(
          visible,
          '    ',
          (b) => contextForScope(roots, b.contribution.entry.scope, 'context'),
          'server',
          options,
        ),
        roots,
        'server',
        '    ',
        scope,
      ),
      ...here.map((hatch) => `    ...await at(${hatch.identifier}, ${innermost}),`),
    ];
    if (body.length === 0 && roots.length === 0) continue;
    if (roots.length > 0) usesRoots = true;
    const factory = scopeBody(rootPrologue(roots, 'context'), rootHooks(roots), body, '  ');
    scopes.push(`  ${scope}: ${factory[0]}`, ...factory.slice(1));
  }

  return compact([
    HEADER,
    serverImport(scopes),
    ...(usesRoots ? ["import { composeRootHooks } from '@agimon-ai/doompi-core/extension-file';"] : []),
    '',
    ...importsFor(bindings, hatches, allRoots, options.entryDir),
    '',
    ...resolverFor(scopes),
    'export const facet = defineServerPlugin({',
    `  name: '${options.packageName}',`,
    ...scopes,
    '});',
    '',
    'export default facet;',
    '',
  ]);
}

/**
 * The cockpit entry, one contributions object per scope.
 *
 * No cascade here, unlike the server: the registry already folds global into
 * workspace into session before install, so repeating a contribution would
 * install it twice.
 */
export function renderWebEntry(resolution: TargetResolution, options: RenderOptions): string {
  const bindings = bind(resolution, options);
  const hatches = hatchBindings(resolution.escapeHatches);

  const scopes: string[] = [];
  for (const scope of SCOPE_ORDER) {
    const visible = bindings.filter((b) => b.contribution.entry.scope === scope);
    const here = hatches.filter((h) => h.entry.scope === scope);
    const body = [
      ...bodyFor(visible, '    ', () => 'undefined', 'web', options),
      // Frontend escape hatches are contribution data. Calling them would also
      // call React components, so merge the authored object directly.
      ...here.map((hatch) => `    ...${hatch.identifier},`),
    ];
    if (body.length === 0) continue;
    scopes.push(`  ${scope}: {`, ...body, '  },');
  }

  return compact([
    HEADER,
    scopes.some((line) => line.includes('get '))
      ? "import { defineWebPlugin, type WebPluginContributions } from '@agimon-ai/doompi-core/web';"
      : "import { defineWebPlugin } from '@agimon-ai/doompi-core/web';",
    '',
    ...importsFor(bindings, hatches, [], options.entryDir),
    '',
    ...resolverFor(scopes),
    'export const webPlugin = defineWebPlugin({',
    `  id: '${options.pluginId}',`,
    ...scopes,
    '});',
    '',
  ]);
}
