import type { ExtensionEntry, ExtensionScope } from '../../types/extensionGraph';
import { type Identity, renderIdentity, toKebab, toSnake } from '../identity';
import type { BuildTarget, ResolvedContribution, TargetResolution } from '../resolveTarget/type';
import type { RenderOptions } from './type';

const HEADER = '// Generated by @agimon-ai/doompi-build. Do not edit by hand.';

/** The one field that is a record keyed by event name rather than an array. */
const RECORD_FIELDS: readonly string[] = ['events'];

/** The one field whose members are factories rather than declarations. */
const FACTORY_FIELDS: readonly string[] = ['channels'];

const SCOPE_ORDER: readonly ExtensionScope[] = ['global', 'workspace', 'session'];

/**
 * Resolves a routed file's default export, which may be the declaration or a
 * factory of one. Both host helpers already accept either shape, so a
 * generated entry has to as well. Emitted rather than imported, so a generated
 * entry carries no runtime dependency beyond the helper it is calling.
 */
const RESOLVER = [
  'type Factory<T> = (context: unknown) => T;',
  'const at = <T,>(value: T | Factory<T>, context: unknown): T =>',
  "  typeof value === 'function' ? (value as Factory<T>)(context) : value;",
].join('\n');

/**
 * Every fill is a slot fill. There is no host-region special case.
 *
 * The cockpit's own regions are slots like any other: an activity section
 * already renders into `activity.<group>`, which is why naming the target
 * directly works for a host region and a plugin's slot alike. Keeping this
 * uniform is what lets a layout package declare new regions without the build
 * tooling learning about them.
 */
function fillIdentity(name: string, target: string | undefined): Identity {
  if (target === undefined) return { id: toKebab(name) };
  return { slot: target, id: toKebab(name) };
}

/** What the path can tell each host, keyed by the folder the author typed. */
const BACKEND_IDENTITY: Readonly<Record<string, (name: string) => Identity>> = {
  tool: (name) => ({ name: toSnake(name) }),
  command: (name) => ({ name: toSnake(name) }),
  channel: (name) => ({ frameType: toSnake(name) }),
  // Only the server reads this; the CLI keys its events record by the same name.
  hook: (name) => ({ event: toSnake(name) }),
  mode: (name) => ({ name: toKebab(name) }),
};

const FRONTEND_IDENTITY: Readonly<Record<string, (name: string, options: RenderOptions) => Identity>> = {
  tool: (name) => ({ tools: [toSnake(name)] }),
  channel: (name) => ({ channel: toSnake(name) }),
  slot: (name, options) => ({ slot: `${options.pluginId}.${toKebab(name)}` }),
  command: (name) => ({ id: toKebab(name) }),
  tab: (name) => ({ id: toKebab(name) }),
  dock: (name) => ({ id: toKebab(name) }),
  setting: (name) => ({ id: toKebab(name) }),
  action: (name) => ({ id: toKebab(name) }),
  mode: (name) => ({ name: toKebab(name) }),
};

/**
 * What the path knows about a contribution's identity.
 *
 * Keyed by surface, because the folder is what the author types. A surface
 * absent from the table, or an identity the path cannot supply such as a tab's
 * human label, is left entirely to the authored file.
 */
function identityFor(
  contribution: ResolvedContribution,
  target: BuildTarget,
  options: RenderOptions,
): Identity | undefined {
  const { entry } = contribution;
  const surface = entry.surface;
  if (surface === undefined) return undefined;

  if (target !== 'web') return BACKEND_IDENTITY[surface]?.(entry.name);
  if (surface === 'fill') return fillIdentity(entry.name, entry.target);
  return FRONTEND_IDENTITY[surface]?.(entry.name, options);
}

/** A stable, unique, valid identifier: surface and name, disambiguated by scope when needed. */
function identifierFor(contribution: ResolvedContribution, taken: Set<string>): string {
  const words = [contribution.entry.surface ?? 'extra', contribution.entry.name]
    .join('-')
    .split(/[^A-Za-z0-9]+/u)
    .filter((word) => word.length > 0);
  const head = words.map((word, index) => (index === 0 ? word : word[0]?.toUpperCase() + word.slice(1))).join('');
  const base = /^[A-Za-z_]/u.test(head) ? head : `x${head}`;
  let candidate = base;
  let suffix = 2;
  while (taken.has(candidate)) candidate = `${base}${suffix++}`;
  taken.add(candidate);
  return candidate;
}

/** The extensionless relative specifier from a generated entry to a routed file. */
function specifierFor(file: string, root: string): string {
  return `./${file.slice(root.length + 1).replace(/\.[^.]+$/u, '')}`;
}

interface Binding {
  readonly identifier: string;
  readonly contribution: ResolvedContribution;
  readonly identity: Identity | undefined;
}

function bind(resolution: TargetResolution, options: RenderOptions): Binding[] {
  const taken = new Set<string>();
  return [...resolution.contributions]
    .sort((left, right) => left.entry.file.localeCompare(right.entry.file))
    .map((contribution) => ({
      identifier: identifierFor(contribution, taken),
      contribution,
      identity: identityFor(contribution, resolution.target, options),
    }));
}

function hatchBindings(entries: readonly ExtensionEntry[]): { identifier: string; entry: ExtensionEntry }[] {
  return [...entries]
    .sort((left, right) => left.file.localeCompare(right.file))
    .map((entry, index) => ({ identifier: `extra${index === 0 ? '' : index + 1}`, entry }));
}

/** One contribution as it appears inside its array, identity first so the file wins. */
function member(binding: Binding, contextExpression: string): string {
  const resolved = `at(${binding.identifier}, ${contextExpression})`;
  const isFactory = FACTORY_FIELDS.includes(binding.contribution.field);
  if (binding.identity === undefined) return isFactory ? binding.identifier : resolved;

  const identity = renderIdentity(binding.identity);
  // A channel array holds factories, so the identity is merged inside one.
  if (isFactory) return `() => ({ ${identity}, ...${binding.identifier}() })`;
  return `{ ${identity}, ...${resolved} }`;
}

function bodyFor(bindings: readonly Binding[], indent: string, contextExpression: string): string[] {
  const grouped = new Map<string, Binding[]>();
  for (const binding of bindings) {
    const held = grouped.get(binding.contribution.field);
    if (held === undefined) grouped.set(binding.contribution.field, [binding]);
    else held.push(binding);
  }

  const lines: string[] = [];
  for (const field of [...grouped.keys()].sort()) {
    const members = grouped.get(field) as Binding[];
    if (RECORD_FIELDS.includes(field)) {
      lines.push(`${indent}${field}: {`);
      for (const entry of members) {
        lines.push(
          `${indent}  ${toSnake(entry.contribution.entry.name)}: at(${entry.identifier}, ${contextExpression}),`,
        );
      }
      lines.push(`${indent}},`);
      continue;
    }
    lines.push(`${indent}${field}: [${members.map((entry) => member(entry, contextExpression)).join(', ')}],`);
  }
  return lines;
}

function importsFor(
  bindings: readonly Binding[],
  hatches: readonly { identifier: string; entry: ExtensionEntry }[],
  root: string,
): string[] {
  return [
    ...bindings.map((b) => `import ${b.identifier} from '${specifierFor(b.contribution.entry.file, root)}';`),
    ...hatches.map((h) => `import ${h.identifier} from '${specifierFor(h.entry.file, root)}';`),
  ];
}

function compact(lines: readonly string[]): string {
  return lines.filter((line, index, all) => !(line === '' && all[index - 1] === '')).join('\n');
}

/**
 * Emits the resolver only when something calls it.
 *
 * Extension packages compile with noUnusedLocals, so a generated entry whose
 * every contribution is a factory would otherwise fail to typecheck on an
 * unused helper.
 */
function resolverFor(body: readonly string[]): string[] {
  return body.some((line) => line.includes('at(')) ? [RESOLVER, ''] : [];
}

/** `noUnusedParameters` means a scope that never threads context takes none. */
function parameterFor(body: readonly string[]): string {
  return body.some((line) => line.includes(', context)')) ? '(context)' : '()';
}

/** The interactive terminal entry. One mount, so every backend contribution lands in it. */
export function renderCliEntry(resolution: TargetResolution, options: RenderOptions): string {
  const bindings = bind(resolution, options);
  const hatches = hatchBindings(resolution.escapeHatches);
  const body = [
    ...bodyFor(bindings, '  ', 'context'),
    ...hatches.map((hatch) => `  ...at(${hatch.identifier}, context),`),
  ];

  return compact([
    HEADER,
    "import { definePiExtension } from '@agimon-ai/doompi-core/pi-extension';",
    '',
    ...importsFor(bindings, hatches, options.root),
    '',
    ...resolverFor(body),
    `export const extension = definePiExtension('${options.packageName}', ${parameterFor(body)} => ({`,
    ...body,
    '}));',
    '',
    'export default extension;',
    '',
  ]);
}

/**
 * The headless entry, one declaration per scope.
 *
 * Contributions cascade downward here because the server does not do it
 * itself: a facet reads exactly one `plugin[host.scope]` and nothing from the
 * scopes above it. Emitting the repetition is what lets an author declare a
 * channel once and have it mount at all three scopes.
 */
export function renderServerEntry(resolution: TargetResolution, options: RenderOptions): string {
  const bindings = bind(resolution, options);
  const hatches = hatchBindings(resolution.escapeHatches);

  const scopes: string[] = [];
  for (const [index, scope] of SCOPE_ORDER.entries()) {
    const visible = bindings.filter((b) => SCOPE_ORDER.indexOf(b.contribution.entry.scope) <= index);
    const here = hatches.filter((h) => SCOPE_ORDER.indexOf(h.entry.scope) <= index);
    const body = [
      ...bodyFor(visible, '    ', 'context'),
      ...here.map((hatch) => `    ...at(${hatch.identifier}, context),`),
    ];
    if (body.length === 0) continue;
    scopes.push(`  ${scope}: ${parameterFor(body)} => ({`, ...body, '  }),');
  }

  return compact([
    HEADER,
    "import { defineServerPlugin } from '@agimon-ai/doompi-core/server-facet';",
    '',
    ...importsFor(bindings, hatches, options.root),
    '',
    ...resolverFor(scopes),
    'export const facet = defineServerPlugin({',
    `  name: '${options.packageName}',`,
    ...scopes,
    '});',
    '',
    'export default facet;',
    '',
  ]);
}

/**
 * The cockpit entry, one contributions object per scope.
 *
 * No cascade here, unlike the server: the registry already folds global into
 * workspace into session before install, so repeating a contribution would
 * install it twice.
 */
export function renderWebEntry(resolution: TargetResolution, options: RenderOptions): string {
  const bindings = bind(resolution, options);
  const hatches = hatchBindings(resolution.escapeHatches);

  const scopes: string[] = [];
  for (const scope of SCOPE_ORDER) {
    const visible = bindings.filter((b) => b.contribution.entry.scope === scope);
    const here = hatches.filter((h) => h.entry.scope === scope);
    const body = [
      ...bodyFor(visible, '    ', 'undefined'),
      ...here.map((hatch) => `    ...at(${hatch.identifier}, undefined),`),
    ];
    if (body.length === 0) continue;
    scopes.push(`  ${scope}: {`, ...body, '  },');
  }

  return compact([
    HEADER,
    "import { defineWebPlugin } from '@agimon-ai/doompi-core/web';",
    '',
    ...importsFor(bindings, hatches, options.root),
    '',
    ...resolverFor(scopes),
    'export const webPlugin = defineWebPlugin({',
    `  id: '${options.pluginId}',`,
    ...scopes,
    '});',
    '',
  ]);
}
