import { defineConfig } from 'tsdown';

export default defineConfig({
  entry: {
    'builders/web': 'src/exports/webBuilder.ts',
    'extensions/context-catalog': 'src/extensions/contextCatalog.ts',
    index: 'src/exports/index.ts',
    'bin/cli': 'src/bin/cli.ts',
    'bin/doomRunner': 'src/bin/doomRunner.ts',
    'bin/dpi': 'src/bin/dpi.ts',
    cli: 'src/exports/cli.ts',
    'cli-app': 'src/exports/cliApp.ts',
    'compatibility-options': 'src/exports/compatibilityOptions.ts',
    help: 'src/exports/help.ts',
    'matrix-options': 'src/exports/matrixOptions.ts',
    options: 'src/exports/options.ts',
    commands: 'src/exports/commands.ts',
    'base-command': 'src/exports/baseCommand.ts',
    'compatibility-command': 'src/exports/compatibilityCommand.ts',
    'emit-mcp-command': 'src/exports/emitMcpCommand.ts',
    'explain-command': 'src/exports/explainCommand.ts',
    'init-command': 'src/exports/initCommand.ts',
    'launch-command': 'src/exports/launchCommand.ts',
    'sync-command': 'src/exports/syncCommand.ts',
    config: 'src/exports/config.ts',
    'harness-state': 'src/exports/harnessState.ts',
    'project-trust': 'src/exports/projectTrust.ts',
    'extensions/pi': 'src/extensions/pi.ts',
    'extensions/server': 'src/extensions/server.ts',
    'extensions/agent-model': 'src/extensions/agentModel.ts',
    'extensions/cordis-finalizer': 'src/extensions/cordisFinalizer.ts',
    'extensions/cordis-host': 'src/extensions/cordisHost.ts',
    'extensions/composed-pi': 'src/extensions/composedPi.ts',
    'extensions/effort': 'src/extensions/effort.ts',
    'extensions/terminal-child-session': 'src/extensions/terminalChildSession.ts',
    'extensions/ollama-provider': 'src/extensions/ollamaProvider.ts',
    'extensions/style-system': 'src/extensions/styleSystem.ts',
    services: 'src/exports/services.ts',
    compatibility: 'src/exports/compatibility.ts',
    antigravity: 'src/exports/antigravity.ts',
    codex: 'src/exports/codex.ts',
    process: 'src/exports/process.ts',
    shared: 'src/exports/shared.ts',
    'compatibility-context': 'src/exports/compatibilityContext.ts',
    composer: 'src/exports/composer.ts',
    'harness-context': 'src/exports/harnessContext.ts',
    'matrix-switcher': 'src/exports/matrixSwitcher.ts',
    'mcp-filter': 'src/exports/mcpFilter.ts',
    'resource-collector': 'src/exports/resourceCollector.ts',
    'sync-state': 'src/exports/syncState.ts',
    utils: 'src/exports/utils.ts',
    repository: 'src/exports/repository.ts',
    'extensions/launcher-bootstrap': 'src/extensions/launcherBootstrap.ts',
    'extensions/transition-coordinator': 'src/extensions/transitionCoordinator.ts',
    'bin/serve': 'src/bin/serve.ts',
    'builders/cli/index': 'src/builders/cli/index.ts',
    'builders/cli/extensionAssembler/index': 'src/builders/cli/extensionAssembler/index.ts',
  },
  clean: true,
  dts: { incremental: true, parallel: false, eager: true },
  exports: false,
  format: ['esm', 'cjs'],
  platform: 'node',
  sourcemap: true,
  unbundle: true,
});
