import { defineConfig } from 'tsdown';

const runtimeEntries = {
  '*': ['src/exports/**/*.ts', '!src/exports/apiContracts.ts'],
  runtimeCordisHost: 'src/pi/cordisHost.ts',
  toolInventory: 'src/services/toolInventory/index.ts',
  moduleResolution: 'src/services/moduleResolution/index.ts',
  webCompositions: 'src/services/webCompositions/index.ts',
  syncLocation: 'src/services/syncLocation/index.ts',
  runtimeLogSinkTelemetry: 'src/services/logSinkTelemetry/index.ts',
  syncRegistration: 'src/services/syncRegistration/index.ts',
  headlessHub: 'src/server/headlessHub.ts',
  headlessSessionManager: 'src/systems/main/adapters/headlessSessionManager.ts',
  headlessSessionHost: 'src/systems/main/types/headlessSessionHost.ts',
  runtimeHeadlessSessionManager: 'src/systems/main/types/headlessSessionManager.ts',
  packageApiServer: 'src/server/packageApiServer.ts',
  serverTelemetry: 'src/services/serverTelemetry/index.ts',
  headlessServer: 'src/server/headlessServer.ts',
  remoteRuntime: 'src/server/remoteRuntime.ts',
  mcpSchemaCost: 'src/services/mcpSchemaCost/index.ts',
  historyOwnership: 'src/services/historyOwnership/index.ts',
  v3Export: 'src/services/v3Export/index.ts',
  historyImport: 'src/services/historyImport/index.ts',
  jsonlSessionRepo: 'src/services/jsonlSessionRepo/index.ts',
  sqliteHistoryImport: 'src/services/sqliteHistoryImport/index.ts',
  runtimePiSettings: 'src/services/piSettings/index.ts',
  runtimeJson: 'src/services/json/index.ts',
  doomPackage: 'src/services/doomPackage/index.ts',
  transitionClassifier: 'src/services/transitionClassifier/index.ts',
  runtimeIdentity: 'src/services/runtimeIdentity/index.ts',
  runtimeToolNames: 'src/services/toolNames/index.ts',
  contextDetailStore: 'src/services/contextDetailStore/index.ts',
  runtimeContextApi: 'src/server/contextApi.ts',
  sessionFilesApi: 'src/server/sessionFilesApi.ts',
  machineApi: 'src/server/machineApi.ts',
  remoteApi: 'src/server/remoteApi.ts',
  terminalPiChildSessionService: 'src/systems/child/adapters/terminalPiChildSessionService.ts',
  transitionCoordinator: 'src/services/transitionCoordinator/index.ts',
  syncStateContract: 'src/services/syncStateContract/index.ts',
  typesContextApi: 'src/types/contextApi.ts',
  contextDetail: 'src/services/contextDetail/index.ts',
  contextProjection: 'src/services/contextProjection/index.ts',
  sqliteSessionStorage: 'src/services/sqliteSessionStorage/index.ts',
  runtimePiExtension: 'src/extensions/piExtension.ts',
  runtimeConfig: 'src/schemas/config.ts',
  runtimeProtocol: 'src/schemas/protocol.ts',
  runtimeTransition: 'src/schemas/transition.ts',
};

export default defineConfig([
  {
    entry: ['src/exports/apiContracts.ts'],
    clean: true,
    dts: { incremental: true, parallel: false, eager: true },
    exports: false,
    format: ['esm', 'cjs'],
    platform: 'node',
    sourcemap: true,
    // Contract graphs consume only this public entry, so it must carry its
    // implementation rather than import private dist modules.
    unbundle: false,
  },
  {
    entry: runtimeEntries,
    clean: false,
    dts: { incremental: true, parallel: false, eager: true },
    exports: false,
    format: ['esm', 'cjs'],
    platform: 'node',
    sourcemap: true,
    unbundle: true,
  },
]);
