/**
 * The curated icon set. Re-exported from one place so every consumer draws
 * from the same family and a plugin needs no icon dependency of its own.
 */
export {
  Activity as ActivityIcon,
  AudioLines as AudioLinesIcon,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronRight as ChevronRightIcon,
  ChevronUp as ChevronUpIcon,
  CircleAlert as AlertIcon,
  CornerDownLeft as EnterIcon,
  ExternalLink as ExternalLinkIcon,
  FileText as FileIcon,
  GitBranch as BranchIcon,
  Loader2 as LoaderIcon,
  MessageCircle as MessageIcon,
  Mic as MicIcon,
  MoreVertical as KebabIcon,
  Pencil as EditIcon,
  Palette as PaletteIcon,
  Plus as PlusIcon,
  Quote as QuoteIcon,
  RefreshCw as RefreshIcon,
  Rewind as RewindIcon,
  Search as SearchIcon,
  Send as SendIcon,
  Settings as GearIcon,
  ShieldCheck as ShieldIcon,
  Square as StopIcon,
  Trash2 as TrashIcon,
  UserRound as UserIcon,
  Volume2 as VolumeIcon,
  X as CloseIcon,
} from 'lucide-react';
